---
settings:
  name: Active IQ Unified Manager 9.14
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - version-number: '9.14'
    url: "/active-iq-unified-manager"
  - version-number: '9.13'
    url: "/active-iq-unified-manager-913"
  - version-number: '9.12'
    url: "/active-iq-unified-manager-912"
  - version-number: '9.11'
    url: "/active-iq-unified-manager-911"
  - version-number: '9.10'
    url: "/active-iq-unified-manager-910"
  langs: zh-cn,us-en,ja-jp,ko-kr,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Active IQ Unified Manager 9.14文档
    url: "/index.html"
  - title: 发行说明
    url: "/reference_release_notes.html"
  - title: 入门
    entries:
    - title: 快速开始安装 VMware vSphere
      url: "/install-vapp/qsg-vapp.html"
    - title: 快速开始安装 Linux
      url: "/install-linux/qsg-linux.html"
    - title: 快速开始安装 Windows
      url: "/install-windows/qsg-windows.html"
  - section: install-vapp
  - section: install-linux
  - section: install-windows
  - section: config
  - section: storage-mgmt
  - section: events
  - section: performance-checker
  - section: health-checker
  - section: data-protection
  - section: reporting
  - section: api-automation
  - title: 法律声明
    url: "/legal-notices.html"
