---
permalink: api-automation/concept_api_url_and_categories.html 
sidebar: sidebar 
keywords: active iq, unified manager, api, access, categories 
summary: 通过 Active IQ Unified Manager API ，您可以管理和配置环境中的存储对象。您还可以访问 Unified Manager Web UI 来执行其中某些功能。 
---
= Active IQ Unified Manager API 访问和类别
:icons: font
:imagesdir: ../media/
:pp: &#43;&#43;


[role="lead"]
通过 Active IQ Unified Manager API ，您可以管理和配置环境中的存储对象。您还可以访问 Unified Manager Web UI 来执行其中某些功能。



== 构建 URL 以直接访问 REST API

您可以直接通过编程语言访问 REST API ，例如 Python ， C# ， C ｛ pp ｝ ， JavaScript ， 等等。以格式输入主机名或 IP 地址以及用于访问 REST API 的 URL

+https://<hostname>/api+

[NOTE]
====
默认端口为 443. 。您可以根据环境需要配置端口。

====


== 访问联机 API 文档页面

您可以访问随产品一起打包的 _API Documentation_reference 内容页面，以显示 API 文档，并手动对 API 调用（在接口上，例如 Swagger ）进行问题描述处理。您可以单击 * 菜单栏 * > * 帮助按钮 * > * API 文档 * 来访问此文档

或者，以格式输入主机名或 IP 地址以及用于访问 REST API 页面的 URL

+https://<hostname>/docs/api/+



== 类别

API 调用会根据区域或类别按功能进行组织。要查找特定 API ，请单击相应的 API 类别。

Unified Manager 附带的 REST API 可帮助您执行管理，监控和配置功能。这些 API 分为以下几类。

* * 数据中心 *
+
此类别包含的 API 可帮助您使用工作流自动化和 Ansible 等工具进行数据中心存储管理和分析。此类别下的 REST API 提供有关集群，节点，聚合，卷， LUN ， 文件共享，命名空间和数据中心中的其他元素。

* * 管理服务器 *
+
"* 管理服务器 * " 类别下的 API 包含 `作业，系统，` 和 `事件` API 。作业是指计划在 Unified Manager 上执行的与管理存储对象或工作负载相关的异步执行操作。`Events` API 将返回数据中心中的事件，而 `ssystem` API 将返回 Unified Manager 实例详细信息。

* * 存储提供程序 *
+
此类别包含管理和配置文件共享， LUN ，性能服务级别和存储效率策略所需的所有配置 API 。此外，您还可以使用这些 API 配置访问端点， Active Directory 以及为存储工作负载分配性能服务级别和存储效率策略。

* * 管理 *
+
此类别包含用于运行管理任务的 API ，例如维护备份设置，查看 Unified Manager 数据源的信任存储证书以及将 ONTAP 集群作为 Unified Manager 数据源进行管理。

* * 网关 *
+
通过 Unified Manager ，您可以通过网关类别下的 API 调用 ONTAP REST API ，并管理数据中心中的存储对象。

* * 安全性 *
+
此类别包含用于管理 Unified Manager 用户的 API 。


