---
permalink: api-automation/concept_manage_sep.html 
sidebar: sidebar 
keywords: manage, storage, efficiency, policy 
summary: 您可以使用存储提供程序 API 查看，创建，修改和删除存储效率策略。 
---
= 管理存储效率策略
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用存储提供程序 API 查看，创建，修改和删除存储效率策略。

[NOTE]
====
请注意以下几点：

* 在 Unified Manager 上创建工作负载时，不必分配存储效率策略。
* 在为工作负载分配存储效率策略后，您不能为其取消分配存储效率策略。
* 如果工作负载在 ONTAP 卷上指定了某些存储设置，例如重复数据删除和数据压缩，则这些设置可能会被在 Unified Manager 上添加存储工作负载时应用的存储效率策略中指定的设置所覆盖。


====


== 查看存储效率策略

在将存储效率策略分配给存储工作负载之前，您可以使用以下方法查看这些策略。此 API 将列出所有系统定义的和用户创建的存储效率策略，并检索所有存储效率策略的属性。如果要查询特定的存储效率策略，则需要输入该策略的唯一 ID 来检索其详细信息。

[cols="3*"]
|===
| 类别 | HTTP 动词 | 路径 


 a| 
存储提供程序
 a| 
获取
 a| 
` 存储提供程序 / 存储效率策略`

` 存储提供程序 /storage-efficiency-policies/\ ｛ key ｝`

|===


== 添加存储效率策略

您可以使用以下方法创建自定义存储效率策略，并在系统定义的策略不满足存储工作负载的配置要求时将其分配给存储工作负载。输入要创建的存储效率策略的详细信息作为输入参数。

[cols="3*"]
|===
| 类别 | HTTP 动词 | 路径 


 a| 
存储提供程序
 a| 
发布
 a| 
` 存储提供程序 / 存储效率策略`

|===


== 删除存储效率策略

您可以使用以下方法删除特定的存储效率策略。如果存储效率策略已分配给工作负载，或者它是唯一可用的存储效率策略，则不能将其删除。要删除特定的存储效率策略，您需要提供存储效率策略的唯一 ID 作为输入参数。

[cols="3*"]
|===
| 类别 | HTTP 动词 | 路径 


 a| 
存储提供程序
 a| 
删除
 a| 
` 存储提供程序 /storage-efficiency-policies/\ ｛ key ｝`

|===


== 修改存储效率策略

您可以使用以下方法修改存储效率策略并更新其属性。您不能修改系统定义的或分配给工作负载的存储效率策略。要修改特定的存储效率策略，您需要提供存储效率策略的唯一 ID 。此外，您还需要提供要更新的属性及其值。

[cols="3*"]
|===
| 类别 | HTTP 动词 | 路径 


 a| 
存储提供程序
 a| 
patch
 a| 
` 存储提供程序 /storage-efficiency-policies/\ ｛ key ｝`

|===