---
permalink: api-automation/concept_events_api.html 
sidebar: sidebar 
keywords: view, events, system, details 
summary: 通过事件 API ，您可以检索为数据中心中受监控集群生成的事件。 
---
= 管理事件和警报
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用 `manmanagement-server` 类别下的 `Events` ， `alAlerts` 和 `sscripts` API ，您可以管理 Active IQ Unified Manager 环境中与警报关联的事件，警报和脚本。



== 查看和修改事件

Unified Manager 将接收在 ONTAP 上为 Unified Manager 监控和管理的集群生成的事件。通过使用这些 API ，您可以查看为集群生成的事件，并解决和更新这些事件。

通过对 ` /management-server/events` API 运行 `get` 方法，您可以查询数据中心中的事件，包括历史数据。使用内置筛选器，例如名称，影响级别，影响区域，严重性， 状态，资源名称和资源类型，用于查看特定事件。资源类型和区域参数返回有关发生事件的存储对象的信息，而影响区域返回有关引发事件的问题描述的信息，例如可用性，容量，配置，安全性， 保护和性能。

通过对此 API 运行修补操作，您可以为此事件启用解析工作流。您可以将事件分配给自己或其他用户，并确认收到事件。在对资源执行步骤以解决触发事件的问题描述时，您可以使用此 API 将事件标记为已解决。

有关事件的详细信息，请参见 link:../events/concept_manage_events.html["管理事件"]

[cols="4*"]
|===
| 类别 | HTTP 动词 | 路径 | Description 


 a| 
管理服务器
 a| 
获取
 a| 
` /management-server/events` ` /management-server/events/ ｛ key ｝`
 a| 
运行 GET ALL 方法时，响应正文由数据中心中所有事件的事件详细信息组成。通过特定密钥检索事件详细信息时，您可以查看特定事件的详细信息并对资源运行下一组操作。响应正文由该事件的详细信息组成。



 a| 
管理服务器
 a| 
patch
 a| 
`manmanagement-server/events/ ｛ key ｝`
 a| 
运行此 API 以分配事件或将状态更改为已确认或已解决。您也可以使用此方法将事件分配给您自己或其他用户。这是一种同步操作。

|===


== 管理警报

系统会自动持续生成事件。只有当事件满足特定筛选条件时， Unified Manager 才会生成警报。您可以选择应生成警报的事件。通过使用 ` /management-server/alers` API ，您可以配置警报，以便在发生特定事件或特定严重性类型的事件时自动发送通知。

有关警报的详细信息，请参见 link:../events/concept_manage_alerts.html["管理警报"]

[cols="4*"]
|===
| 类别 | HTTP 动词 | 路径 | Description 


 a| 
管理服务器
 a| 
获取
 a| 
` /management-server/alers` ` /management-server/alers/ ｛ key ｝`
 a| 
使用警报密钥查询环境中的所有现有警报或特定警报。您可以查看有关环境中生成的警报的信息，例如警报问题描述，操作，将通知发送到的电子邮件 ID ，事件和严重性。



 a| 
管理服务器
 a| 
发布
 a| 
` 管理服务器 / 警报`
 a| 
使用此方法可以为特定事件添加警报。您必须添加警报名称，适用于警报的物理或逻辑资源或事件，是否已启用警报以及是否正在发出 SNMP 陷阱。您可以添加要生成警报的其他详细信息，例如操作，通知电子邮件 ID ，脚本详细信息等，以便在添加警报脚本时使用。



 a| 
管理服务器
 a| 
修补并删除
 a| 
`manmanagement-server/events/ ｛ key ｝`
 a| 
您可以使用这些方法修改和删除特定警报。您可以修改不同的属性，例如问题描述，名称以及启用和禁用警报。您可以在不再需要警报时删除此警报。

|===

NOTE: 在选择用于添加警报的资源时，请注意，选择集群作为资源不会自动选择该集群中的存储对象。例如，如果为所有集群的所有严重事件创建警报，则只会收到集群严重事件的警报。您不会收到节点，聚合等上的严重事件警报。



== 管理脚本

通过使用 ` /management-server/scripts` API ，您还可以将警报与触发警报时执行的脚本相关联。您可以使用脚本在 Unified Manager 中自动修改或更新多个存储对象。此脚本与警报关联。当事件触发警报时，将执行脚本。您可以上传自定义脚本，并在生成警报时测试其执行情况。您可以将警报与脚本关联，以便在 Unified Manager 中针对事件发出警报时执行脚本。

有关脚本的详细信息，请参见 link:../events/concept_manage_scripts.html["管理脚本"]

[cols="4*"]
|===
| 类别 | HTTP 动词 | 路径 | Description 


 a| 
管理服务器
 a| 
获取
 a| 
` 管理服务器 / 脚本`
 a| 
使用此 API 查询环境中的所有现有脚本。使用标准筛选器和按顺序操作仅查看特定脚本。



 a| 
管理服务器
 a| 
发布
 a| 
` 管理服务器 / 脚本`
 a| 
使用此 API 为脚本添加问题描述并上传与警报关联的脚本文件。

|===