---
permalink: api-automation/concept_metrics_apis.html 
sidebar: sidebar 
keywords: view, performance, metrics 
summary: 'Active IQ Unified Manager 在 /datacenter" 类别下为您提供了一组 API ，可用于查看数据中心中集群和存储对象的性能数据。这些 API 会检索不同存储对象的性能数据，例如集群，节点， LUN ，卷， 聚合和 Storage VM 。' 
---
= 使用API查看性能指标
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager 在 ` 或数据中心` 类别下为您提供了一组 API ，可用于查看数据中心中集群和存储对象的性能数据。这些 API 可检索不同存储对象的性能数据，例如集群，节点， LUN ，卷，聚合， Storage VM ， FC 接口， FC 端口，以太网端口和 IP 接口。

` 度量指标` 和 ` 度量指标 / 分析` API 提供了不同的性能指标视图，使用这些视图，您可以深入了解数据中心中以下存储对象的不同详细级别：

* 集群
* nodes
* Storage VM
* 聚合
* volumes
* LUN
* FC 接口
* FC 端口
* 以太网端口
* IP 接口


下表对 ` 或指标` 和 ` / 分析` API 与检索到的性能数据的详细信息进行了比较。

[cols="2*"]
|===
| 指标 | 分析 


 a| 
单个对象的性能详细信息。例如， ` datacenter/clusters/\ ｛ key ｝ /metrics` API 要求输入集群密钥作为路径参数，以便检索该特定集群的指标。
 a| 
数据中心中多个相同类型对象的性能详细信息。例如， ` /datacenter/cluster/clusters/Analytics` API 检索数据中心中所有集群的汇总指标。



 a| 
基于检索时间间隔参数的存储对象性能指标示例。
 a| 
特定类型存储对象在特定时间段（超过 72 小时）内的性能的高级别聚合值。



 a| 
将检索对象的基本详细信息，例如节点或集群的详细信息。
 a| 
未检索到任何特定详细信息。



 a| 
系统会为单个对象检索累积计数器，例如读取，写入，总计和其他计数器，例如最小，最大，第 95 百分位以及一段时间内的平均性能值。
 a| 
对于同一类型的所有对象，将显示一个聚合值。



 a| 
时间范围和示例数据基于以下计划：数据的时间范围。示例可以是 1 小时， 12 小时， 1 天， 2 天， 3 天， 15d ， 1 瓦， 1 米， 2 米， 3 米， 6 万。如果范围超过 3 天（ 72 小时），则可以获得 1 小时的样本，否则为 5 分钟的样本。每个时间范围的时间段如下：

* 1 小时：最近一小时的指标在 5 分钟内取样。
* 12h ：最近 12 小时内的指标在 5 分钟内取样。
* 1d ：最近一天的指标取样时间超过 5 分钟。
* 2D ：最近 2 天在 5 分钟内取样的指标。
* 3D ：最近 3 天在 5 分钟内取样的指标。
* 15d ：在 1 小时内取样的最近 15 天的指标。
* 1 瓦：最近一周的指标取样时间超过 1 小时。
* 1M ：最近一个月内的指标，取样时间超过 1 小时。
* 2M ：最近 2 个月内的指标，取样时间为 1 小时。
* 3m ：最近 3 个月内的指标，取样时间为 1 小时。
* 6 米：最近 6 个月内的指标，取样时间为 1 小时。
+
可用值： 1 小时， 12 小时， 1 天， 2 天， 3 天， 15d ， 1 瓦， 1 米， 2 米， 3 米， 6 万

+
默认值： 1h


 a| 
超过 72 小时。计算此样本的持续时间以 ISO-8601 标准格式表示。

|===


== 指标API的输出示例

例如、`/datacenter/cluster/nodes/\｛key｝/metrics` API检索节点的以下详细信息(以及其他信息)：


NOTE: 摘要值中的 95 百分位表示为该时间段收集的样本中 95% 的计数器值小于指定的 95 百分位值。

[listing]
----
{
     "iops": {
       "local": {
         "other": 100.53,
         "read": 100.53,
         "total": 100.53,
         "write": 100.53
       },
       "other": 100.53,
       "read": 100.53,
       "total": 100.53,
       "write": 100.53
     },
     "latency": {
       "other": 100.53,
       "read": 100.53,
       "total": 100.53,
       "write": 100.53
     },
     "performance_capacity": {
       "available_iops_percent": 0,
       "free_percent": 0,
       "system_workload_percent": 0,
       "used_percent": 0,
       "user_workload_percent": 0
     },
     "throughput": {
       "other": 100.53,
       "read": 100.53,
       "total": 100.53,
       "write": 100.53
     },
     "timestamp": "2018-01-01T12:00:00-04:00",
     "utilization_percent": 0
   }
 ],
 "start_time": "2018-01-01T12:00:00-04:00",
 "summary": {
   "iops": {
     "local_iops": {
       "other": {
         "95th_percentile": 28,
         "avg": 28,
         "max": 28,
         "min": 5
       },
       "read": {
         "95th_percentile": 28,
         "avg": 28,
         "max": 28,
         "min": 5
       },
       "total": {
         "95th_percentile": 28,
         "avg": 28,
         "max": 28,
         "min": 5
       },
       "write": {
         "95th_percentile": 28,
         "avg": 28,
         "max": 28,
         "min": 5
       }
     },
----


== 分析API的输出示例

例如， ` /datacenter/cluster/nodes/Analytics` API 检索所有节点的以下值（以及其他值）：

[listing]
----
{     "iops": 1.7471,
     "latency": 60.0933,
     "throughput": 5548.4678,
     "utilization_percent": 4.8569,
     "period": 72,
     "performance_capacity": {
       "used_percent": 5.475,
       "available_iops_percent": 168350
     },
     "node": {
       "key": "37387241-8b57-11e9-8974-00a098e0219a:type=cluster_node,uuid=95f94e8d-8b4e-11e9-8974-00a098e0219a",
       "uuid": "95f94e8d-8b4e-11e9-8974-00a098e0219a",
       "name": "ocum-infinity-01",
       "_links": {
         "self": {
           "href": "/api/datacenter/cluster/nodes/37387241-8b57-11e9-8974-00a098e0219a:type=cluster_node,uuid=95f94e8d-8b4e-11e9-8974-00a098e0219a"
         }
       }
     },
     "cluster": {
       "key": "37387241-8b57-11e9-8974-00a098e0219a:type=cluster,uuid=37387241-8b57-11e9-8974-00a098e0219a",
       "uuid": "37387241-8b57-11e9-8974-00a098e0219a",
       "name": "ocum-infinity",
       "_links": {
         "self": {
           "href": "/api/datacenter/cluster/clusters/37387241-8b57-11e9-8974-00a098e0219a:type=cluster,uuid=37387241-8b57-11e9-8974-00a098e0219a"
         },
     "_links": {
       "self": {
         "href": "/api/datacenter/cluster/nodes/analytics"
       }
     }
   },
----


== 可用API的列表

下表详细介绍了 ` / 指标` 和 ` / 分析` API 。

[NOTE]
====
这些 API 返回的 IOPS 和性能指标为双倍值，例如 `100.53` 。不支持使用管道（我们）和通配符（ * ）筛选这些浮点值。

====
[cols="3*"]
|===
| HTTP 动词 | 路径 | Description 


 a| 
`获取`
 a| 
` 数据中心 / 集群 / 集群 // ｛ key ｝ / 指标`
 a| 
检索由集群密钥的输入参数指定的集群的性能数据（示例和摘要）。返回的信息包括集群密钥和 UUID ，时间范围， IOPS ，吞吐量和样本数量。



 a| 
`获取`
 a| 
` 数据中心 / 集群 / 集群 / 分析`
 a| 
检索数据中心中所有集群的高级别性能指标。您可以根据所需条件筛选结果。系统将返回聚合 IOPS ，吞吐量和收集时间段（以小时为单位）等值。



 a| 
`获取`
 a| 
` 数据中心 / 集群 / 节点 // ｛ key ｝ / 指标`
 a| 
检索由节点密钥的输入参数指定的节点的性能数据（示例和摘要）。返回的信息包括节点 UUID ，时间范围， IOPS 摘要，吞吐量，延迟和性能，收集的样本数量以及利用率百分比。



 a| 
`获取`
 a| 
` 数据中心 / 集群 / 节点 / 分析`
 a| 
检索数据中心中所有节点的高级别性能指标。您可以根据所需条件筛选结果。系统将返回节点和集群密钥等信息以及聚合 IOPS ，吞吐量和收集时间段（以小时为单位）等值。



 a| 
`获取`
 a| 
` 数据中心 / 存储 / 聚合 /\ ｛ key ｝ / 指标`
 a| 
检索聚合密钥的输入参数指定的聚合的性能数据（示例和摘要）。返回的信息包括时间范围， IOPS 摘要，延迟，吞吐量和性能容量，为每个计数器收集的样本数以及利用率百分比。



 a| 
`获取`
 a| 
` 数据中心 / 存储 / 聚合 / 分析`
 a| 
检索数据中心中所有聚合的高级别性能指标。您可以根据所需条件筛选结果。系统将返回聚合密钥和集群密钥等信息以及聚合 IOPS ，吞吐量和收集时间段（以小时为单位）等值。



 a| 
`获取`
 a| 
` 数据中心 / 存储 /LUN/\ ｛ key ｝ / 指标`

` 数据中心 / 存储 / 卷 /\ ｛ key ｝ / 指标`
 a| 
检索由 LUN 或卷密钥的输入参数指定的 LUN 或文件共享（卷）的性能数据（示例和摘要）。信息，例如读取，写入和总 IOPS ，延迟和吞吐量的最小值，最大值和平均值摘要， 并返回为每个计数器收集的样本数量。



 a| 
`获取`
 a| 
` 数据中心 / 存储 /LUN/ 分析`

` 数据中心 / 存储 / 卷 / 分析`
 a| 
检索数据中心中所有 LUN 或卷的高级别性能指标。您可以根据所需条件筛选结果。将返回 Storage VM 和集群密钥等信息以及聚合 IOPS ，吞吐量和收集时间段（以小时为单位）等值。



 a| 
`获取`
 a| 
` 数据中心 /SVM/SVM/ ｛ key ｝ / 指标`
 a| 
检索由 Storage VM 密钥的输入参数指定的 Storage VM 的性能数据（示例和摘要）。基于每个受支持协议的 IOPS 摘要，例如 `nvmf ， fcp ， iscsi ，` 和 `nfs` ，吞吐量， 延迟以及返回的样本数量。



 a| 
`获取`
 a| 
` 数据中心 /SVM/SVM/ 分析`
 a| 
检索数据中心中所有 Storage VM 的高级别性能指标。您可以根据所需条件筛选结果。将返回 Storage VM UUID ，聚合 IOPS ，延迟，吞吐量和收集时间段（以小时为单位）等信息。



 a| 
`获取`
 a| 
` 数据中心 / 网络 / 以太网 / 端口 / ｛ key ｝ / 指标`
 a| 
检索由端口密钥的输入参数指定的特定以太网端口的性能指标。如果提供的间隔（时间范围）来自支持的范围，则 API 将返回累积计数器，例如该时间段内的最小，最大和平均性能值。



 a| 
`获取`
 a| 
` 数据中心 / 网络 / 以太网 / 端口 / 分析`
 a| 
检索数据中心环境中所有以太网端口的性能指标概要。返回的信息包括集群和节点密钥和 UUID ，吞吐量，收集期限以及端口的利用率百分比。您可以按可用参数筛选结果，例如端口密钥，利用率百分比，集群和节点名称以及 UUID 等。



 a| 
`获取`
 a| 
` 数据中心 / 网络 /FC/interfaces/｛ key ｝ / 指标`
 a| 
检索由接口密钥的输入参数指定的特定网络 FC 接口的性能指标。如果提供的间隔（时间范围）来自支持的范围，则 API 将返回累积计数器，例如该时间段内的最小，最大和平均性能值。



 a| 
`获取`
 a| 
` 数据中心 / 网络 /FC/接口 / 分析`
 a| 
检索数据中心环境中所有以太网端口的性能指标概要。将返回集群和 FC 接口密钥和 UUID ，吞吐量， IOPS ，延迟和 Storage VM 等信息。您可以按可用参数筛选结果，例如集群和 FC 接口名称和 UUID ， Storage VM ，吞吐量等。



 a| 
`获取`
 a| 
` 数据中心 / 网络 /fc/ 端口 / ｛ key ｝ / 指标`
 a| 
检索由端口密钥的输入参数指定的特定 FC 端口的性能指标。如果提供的间隔（时间范围）来自支持的范围，则 API 将返回累积计数器，例如该时间段内的最小，最大和平均性能值。



 a| 
`获取`
 a| 
` 数据中心 / 网络 /FC/端口 / 分析`
 a| 
检索数据中心环境中所有 FC 端口的性能指标概要。返回的信息包括集群和节点密钥和 UUID ，吞吐量，收集期限以及端口的利用率百分比。您可以按可用参数筛选结果，例如端口密钥，利用率百分比，集群和节点名称以及 UUID 等。



 a| 
`获取`
 a| 
` 数据中心 / 网络 /IP/interfaces/｛ key ｝ / 指标`
 a| 
检索由接口密钥的输入参数指定的网络 IP 接口的性能指标。如果从支持的范围提供间隔（时间范围），则 API 将返回相关信息，例如样本数量，累积计数器，吞吐量以及接收和传输的数据包数量。



 a| 
`获取`
 a| 
` 数据中心 / 网络 /IP/ 接口 / 分析`
 a| 
检索数据中心环境中所有网络 IP 接口的性能指标概要。将返回集群和 IP 接口密钥以及 UUID ，吞吐量， IOPS 和延迟等信息。您可以按可用参数筛选结果，例如集群和 IP 接口名称以及 UUID ， IOPS ，延迟，吞吐量等。

|===