---
permalink: api-automation/concept_data_center_apis.html 
sidebar: sidebar 
keywords: manage, storage, objects, data center 
summary: 通过数据中心类别下的 REST API ，您可以管理数据中心中的存储对象，例如集群，节点，聚合， Storage VM ， 卷， LUN ，文件共享和命名空间。这些 API 可用于查询对象的配置，而其中一些 API 可用于执行添加，删除或修改这些对象的操作。 
---
= 管理数据中心中的存储对象
:icons: font
:imagesdir: ../media/


[role="lead"]
通过 " `d"` 类别下的 REST API ，您可以管理数据中心中的存储对象，例如集群，节点，聚合， Storage VM ， 卷， LUN ，文件共享和命名空间。这些 API 可用于查询对象的配置，而其中一些 API 可用于执行添加，删除或修改这些对象的操作。

其中大多数 API 都是 GET 调用，可提供跨集群聚合以及筛选，排序和分页支持。运行这些 API 时，它们会从数据库返回数据。因此，下一个采集周期需要发现新创建的对象，以便显示在响应中。

如果要查询特定对象的详细信息，则需要输入该对象的唯一 ID 才能查看其详细信息。例如，有关存储对象的指标和分析信息，请参见 link:concept_metrics_apis.html["查看性能指标"]。

[listing]
----
curl -X GET "https://<hostname>/api/datacenter/cluster/clusters/4c6bf721-2e3f-11e9-a3e2-00a0985badbb" -H "accept: application/json" -H "Authorization: Basic <Base64EncodedCredentials>"
----
[NOTE]
====
Swagger API 界面上提供了 cURL 命令，示例，请求和 API 响应。您可以按 Swagger 上指示的特定参数筛选结果并对结果进行排序。通过这些 API ，您可以筛选集群，卷或 Storage VM 等特定存储对象的结果。

====


== 数据中心中存储对象的 API

[cols="3*"]
|===
| HTTP 动词 | 路径 | Description 


 a| 
`获取`
 a| 
` 数据中心 / 集群 / 集群`

` 数据中心 / 集群 / 集群 // ｛ key ｝`
 a| 
您可以使用此方法查看整个数据中心的 ONTAP 集群的详细信息。API 将返回有关节点的信息，例如集群的 IPv4 或 IPv6 地址，节点运行状况，性能容量和高可用性（ HA ）对等信息，并指示集群是否全是 SAN 阵列。



 a| 
`获取`
 a| 
` 数据中心 / 集群 / 许可 / 许可证 /datacenter/ 集群 / 许可 / 许可证 /\ ｛ key ｝``
 a| 
返回数据中心集群上安装的许可证的详细信息。您可以根据所需条件筛选结果。将返回许可证密钥，集群密钥，到期日期和许可证范围等信息。您可以输入许可证密钥以检索特定许可证的详细信息。



 a| 
`获取`
 a| 
` 数据中心 / 集群 / 节点`

` 数据中心 / 集群 / 节点 // ｛ key ｝`
 a| 
您可以使用此方法查看数据中心中节点的详细信息。您可以查看有关节点的集群，节点运行状况，性能容量和高可用性（ HA ）对的信息。



 a| 
`获取`
 a| 
` 数据中心 / 协议 /CIFS/shares`

` 数据中心 / 协议 /CIFS/shares/\ ｛ key ｝`
 a| 
您可以使用此方法查看数据中心中 CIFS 共享的详细信息。除了集群， SVM 和卷详细信息之外，还会返回有关访问控制列表（ ACL ）的信息。



 a| 
`获取`
 a| 
` 数据中心 / 协议 /NFS/export-policies`

` /datacenter/protocols/nfs/export-policies/\ ｛ key ｝`
 a| 
您可以使用此方法查看受支持 NFS 服务的导出策略的详细信息。

您可以查询集群或 Storage VM 的导出策略，并重复使用导出策略密钥来配置 NFS 文件共享。有关在工作负载上分配和重复使用导出策略的详细信息，请参见 "`配置 CIFS 和 NFS 文件共享` " 。



 a| 
`获取`
 a| 
` 数据中心 / 存储 / 聚合`

` 数据中心 / 存储 / 聚合 /\ ｛ key ｝`
 a| 
您可以使用此方法查看数据中心或特定聚合中的聚合集合，以便在这些聚合上配置工作负载或进行监控。将返回集群和节点详细信息，已用性能容量，可用和已用空间以及存储效率等信息。



 a| 
`获取`
 a| 
` 数据中心 / 存储 /LUN`

` 数据中心 / 存储 /LUN/\ ｛ key ｝`
 a| 
您可以使用此方法查看整个数据中心中的 LUN 集合。您可以查看有关 LUN 的信息，例如集群和 SVM 详细信息， QoS 策略和 igroup 。



 a| 
`获取`
 a| 
` 数据中心 / 存储 /QoS/Policies`

` 数据中心 / 存储 /QoS/Policies/\ ｛ key ｝`
 a| 
您可以使用此方法查看适用于数据中心中存储对象的所有 QoS 策略的详细信息。返回的信息包括集群和 SVM 详细信息，固定或自适应策略详细信息以及适用于该策略的对象数量。



 a| 
`获取`
 a| 
` 数据中心 / 存储 /qtree`

` 数据中心 / 存储 /qtree/ ｛ key ｝`
 a| 
您可以使用此方法查看整个数据中心内所有 FlexVol 卷或 FlexGroup 卷的 qtree 详细信息。将返回集群和 SVM 详细信息， FlexVol 卷和导出策略等信息。



 a| 
`获取`
 a| 
` 数据中心 / 存储 / 卷`

` 数据中心 / 存储 / 卷 / ｛ key ｝`
 a| 
您可以使用此方法查看数据中心中的卷集合。返回有关卷的信息，例如 SVM 和集群详细信息， QoS 和导出策略，卷的类型是读写，数据保护还是负载共享。

对于 FlexVol 和 FlexClone 卷，您可以查看有关相应聚合的信息。对于 FlexGroup 卷，查询将返回成分卷聚合的列表。



 a| 
`获取`

`发布`

`d删除`

`修补程序`
 a| 
` 数据中心 / 协议 /SAN/igroup`

` 数据中心 / 协议 /SAN/igroup/ ｛ key ｝`
 a| 
您可以分配有权访问特定 LUN 目标的启动程序组（ igroup ）。如果存在现有 igroup ，您可以对其进行分配。您也可以创建 igroup 并将其分配给 LUN 。

您可以使用这些方法分别查询，创建，删除和修改 igroup 。

需要注意的事项：

* `POST ：` 创建 igroup 时，您可以指定要分配访问权限的 Storage VM 。
* `delete ：` 要删除特定的 igroup ，您需要提供 igroup 密钥作为输入参数。如果已为 LUN 分配 igroup ，则无法删除该 igroup 。
* `patch ：` 您需要提供 igroup 密钥作为输入参数来修改特定的 igroup 。您还必须输入要更新的属性及其值。




 a| 
`获取`

`发布`

`d删除`

`修补程序`
 a| 
` 数据中心 /SVM/SVM`

` 数据中心 /SVM/SVM/\ ｛ key ｝`
 a| 
您可以使用这些方法查看，创建，删除和修改 Storage Virtual Machine （ Storage VM ）。

* `POST ：` 您必须输入要创建的 Storage VM 对象作为输入参数。您可以创建自定义 Storage VM ，然后为其分配所需属性。
* `d：` 您需要提供 Storage VM 密钥才能删除特定 Storage VM 。
* `修补程序：` 要修改特定的 Storage VM ，您需要提供 Storage VM 密钥。您还需要输入要更新的属性及其值。


|===

NOTE: 需要注意的事项：

如果您已在环境中启用基于 SLO 的工作负载配置，则在创建 Storage VM 时，请确保它支持在其上配置 LUN 和文件共享所需的所有协议，例如 CIFS 或 SMB ， NFS ， FCP ， 和 iSCSI 。如果 Storage VM 不支持所需的服务，则配置工作流可能会失败。建议同时在 Storage VM 上为相应类型的工作负载启用服务。

如果您已在环境中启用基于 SLO 的工作负载配置，则无法删除已配置存储工作负载的 Storage VM 。删除已配置 CIFS 或 SMB 服务器的 Storage VM 时，此 API 还会删除 CIFS 或 SMB 服务器以及本地 Active Directory 配置。但是， CIFS 或 SMB 服务器名称仍位于 Active Directory 配置中，您必须从 Active Directory 服务器手动删除此配置。



== 用于数据中心网络元素的 API

数据中心类别中的以下 API 可检索有关环境中的端口和网络接口的信息，尤其是 FC 端口， FC 接口，以太网端口和 IP 接口。

[cols="3*"]
|===
| HTTP 动词 | 路径 | Description 


 a| 
`获取`
 a| 
` 数据中心 / 网络 / 以太网 / 端口`

` 数据中心 / 网络 / 以太网 / 端口 / ｛ key ｝`
 a| 
检索有关数据中心环境中所有以太网端口的信息。使用端口密钥作为输入参数，您可以查看该特定端口的信息。信息，例如集群详细信息，广播域，端口详细信息，例如状态，速度， 检索类型以及端口是否已启用。



 a| 
`获取`
 a| 
` 数据中心 / 网络 /fc/ 接口`

` 数据中心 / 网络 /fc/ 接口 / ｛ key ｝`
 a| 
您可以使用此方法查看数据中心环境中 FC 接口的详细信息。使用接口密钥作为输入参数，您可以查看该特定接口的信息。系统将检索集群详细信息，主节点详细信息和主端口详细信息等信息。



 a| 
`获取`
 a| 
` 数据中心 / 网络 /FC/端口`

` 数据中心 / 网络 /fc/ 端口 / ｛ key ｝`
 a| 
检索有关数据中心环境中节点中使用的所有 FC 端口的信息。使用端口密钥作为输入参数，您可以查看该特定端口的信息。系统将检索集群详细信息，端口问题描述，支持的协议以及端口状态等信息。



 a| 
`获取`
 a| 
` 数据中心 / 网络 /IP/ 接口`

` 数据中心 / 网络 /IP/interfaces/｛ key ｝`
 a| 
您可以使用此方法查看数据中心环境中 IP 接口的详细信息。使用接口密钥作为输入参数，您可以查看该特定接口的信息。系统将检索集群详细信息， IP 空间详细信息，主节点详细信息以及是否已启用故障转移等信息。

|===