---
permalink: api-automation/concept_manage_fileshares_api.html 
sidebar: sidebar 
keywords: manage, file, share 
summary: 您可以使用 /storage-provider/file-shares API 查看，添加，修改和删除数据中心环境中的 CIFS 和 NFS 文件共享卷。 
---
= 使用 API 管理文件共享
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 ` /storage-provider/file-shares` API 查看，添加，修改和删除数据中心环境中的 CIFS 和 NFS 文件共享卷。

在配置文件共享卷之前，请确保已创建 SVM 并使用支持的协议进行配置。如果要在配置期间分配性能服务级别（ PSL ）或存储效率策略（ SEP ），则应在创建文件共享之前创建 PSL 或 SEP 。



== 查看文件共享

您可以使用以下方法查看 Unified Manager 环境中可用的文件共享卷。将 ONTAP 集群添加为 Active IQ Unified Manager 上的数据源后，这些集群的存储工作负载将自动添加到 Unified Manager 实例中。此 API 会自动检索手动添加到 Unified Manager 实例中的文件共享。您可以通过使用文件共享密钥运行此 API 来查看特定文件共享的详细信息。

[cols="3*"]
|===
| 类别 | HTTP 动词 | 路径 


 a| 
存储提供程序
 a| 
获取
 a| 
` 存储提供程序 / 文件共享`

` /storage-provider/file-shares/\ ｛ key ｝`

|===


== 添加文件共享

您可以使用以下方法在 SVM 中添加 CIFS 和 NFS 文件共享。您必须输入要创建的文件共享的详细信息作为输入参数。您不能使用此 API 添加 FlexGroup 卷。

[cols="3*"]
|===
| 类别 | HTTP 动词 | 路径 


 a| 
存储提供程序
 a| 
发布
 a| 
` 存储提供程序 / 文件共享`

|===
[NOTE]
====
根据提供的是访问控制列表（ ACL ）参数还是导出策略参数，系统会创建 CIFS 共享或 NFS 文件共享。如果不提供 ACL 参数的值，则不会创建 CIFS 共享，并且默认情况下会创建 NFS 共享，以便可以访问所有。

====
* 创建数据保护卷 * ：向 SVM 添加文件共享时，默认情况下挂载的卷类型为 `RW` （读写）。要创建数据保护（ DP ）卷，请指定 `dp` 作为 `type` 参数的值。



== 删除文件共享

您可以使用以下方法删除特定文件共享。要删除特定文件共享，您需要输入文件共享密钥作为输入参数。

[cols="3*"]
|===
| 类别 | HTTP 动词 | 路径 


 a| 
存储提供程序
 a| 
删除
 a| 
` /storage-provider/file-shares/\ ｛ key ｝`

|===


== 修改文件共享

您可以使用以下方法修改文件共享并更新其属性。

要修改特定的文件共享，您需要提供文件共享密钥。此外，您还需要输入要更新的属性及其值。

[NOTE]
====
请注意，一次调用此 API 时只能更新一个属性。对于多个更新，您需要多次运行此 API 。

====
[cols="3*"]
|===
| 类别 | HTTP 动词 | 路径 


 a| 
存储提供程序
 a| 
patch
 a| 
` /storage-provider/file-shares/\ ｛ key ｝`

|===