---
permalink: performance-checker/concept_cluster_components_and_why_they_can_be_in_contention.html 
sidebar: sidebar 
keywords: cluster, components, why, contention 
summary: 您可以在集群组件发生争用时确定集群性能问题。使用此组件的工作负载的性能下降，其客户端请求响应时间（延迟）增加，从而在 Unified Manager 中触发事件。 
---
= 集群组件及其可能发生争用的原因
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在集群组件发生争用时确定集群性能问题。使用此组件的工作负载的性能下降，其客户端请求响应时间（延迟）增加，从而在 Unified Manager 中触发事件。

处于争用状态的组件无法以最佳性能运行。其性能已下降，而其他集群组件和工作负载（称为 _victims_） 的性能可能会增加延迟。要使某个组件摆脱争用状态，您必须减少其工作负载或提高其处理更多工作的能力，以使性能恢复到正常水平。由于 Unified Manager 每五分钟收集并分析一次工作负载性能，因此只有在集群组件持续过度使用时，它才会检测到这种情况。不会检测到在五分钟间隔内持续很短时间的瞬时过度使用峰值。

例如，某个存储聚合可能处于争用状态，因为该聚合上的一个或多个工作负载正在争用它们的 I/O 请求来满足。聚合上的其他工作负载可能会受到影响，从而导致其性能下降。要减少聚合上的活动量，您可以采取不同的步骤，例如将一个或多个工作负载移动到不太繁忙的聚合或节点，以减少当前聚合上的整体工作负载需求。对于 QoS 策略组，您可以调整吞吐量限制或将工作负载移动到其他策略组，以使这些工作负载不再受到限制。

Unified Manager 会监控以下集群组件，以便在它们处于争用状态时向您发出警报：

* * 网络 *
+
表示集群上外部网络协议发出的 I/O 请求的等待时间。等待时间是指集群在响应 I/O 请求之前等待 "`transfer ready` " 事务完成所花费的时间。如果网络组件处于争用状态，则表示协议层的等待时间较长，正在影响一个或多个工作负载的延迟。

* * 网络处理 *
+
表示协议层和集群之间的 I/O 处理所涉及的集群软件组件。自检测到事件以来，处理网络处理的节点可能已发生更改。如果网络处理组件处于争用状态，则表示网络处理节点上的高利用率正在影响一个或多个工作负载的延迟。

+
在主动 - 主动配置中使用全 SAN 阵列集群时，将显示两个节点的网络处理延迟值，以便您可以验证这些节点是否均衡共享负载。

* * QoS 限制最大值 *
+
表示分配给工作负载的存储服务质量（ QoS ）策略组的最大吞吐量（峰值）设置。如果策略组组件处于争用状态，则表示策略组中的所有工作负载都受到所设置的吞吐量限制的限制，从而影响一个或多个工作负载的延迟。

* * QoS 限制最小值 *
+
表示分配给其他工作负载的 QoS 吞吐量最小值（预期）设置所导致的工作负载延迟。如果为某些工作负载设置的 QoS 最小值使用大部分带宽来保证承诺的吞吐量，则其他工作负载将受到限制，并会出现更多延迟。

* * 集群互连 *
+
表示与集群节点物理连接的缆线和适配器。如果集群互连组件处于争用状态，则表示集群互连中 I/O 请求的等待时间较长，正在影响一个或多个工作负载的延迟。

* * 数据处理 *
+
表示集群中与工作负载所在的存储聚合之间的 I/O 处理所涉及的集群软件组件。自检测到事件以来，处理数据处理的节点可能已发生更改。如果数据处理组件处于争用状态，则表示数据处理节点上的高利用率正在影响一个或多个工作负载的延迟。

* * 卷激活 *
+
表示跟踪所有活动卷使用情况的过程。在活动卷超过 1000 个的大型环境中，此过程会跟踪需要同时通过节点访问资源的关键卷数量。如果并发活动卷数超过建议的最大阈值，则某些非关键卷将出现此处所述的延迟。

* * MetroCluster 资源 *
+
表示用于在 MetroCluster 配置中的集群之间镜像数据的 MetroCluster 资源，包括 NVRAM 和交换机间链路（ ISL ）。如果 MetroCluster 组件处于争用状态，则表示本地集群上的工作负载写入吞吐量较高，或者链路运行状况问题描述正在影响本地集群上一个或多个工作负载的延迟。如果集群不在 MetroCluster 配置中，则不会显示此图标。

* * 聚合或 SSD 聚合操作 *
+
表示运行工作负载的存储聚合。如果聚合组件处于争用状态，则表示聚合上的高利用率正在影响一个或多个工作负载的延迟。聚合由所有 HDD 组成，或者由 HDD 和 SSD 组成（ Flash Pool 聚合），或者由 HDD 和云层组成（ FabricPool 聚合）。" `SSD 聚合` " 由所有 SSD （全闪存聚合）组成，或者由 SSD 和云层（ FabricPool 聚合）组成。

* * 云延迟 *
+
表示集群中与存储用户数据的云层之间的 I/O 处理相关的软件组件。如果云延迟组件处于争用状态，则表示从云层上托管的卷进行的大量读取正在影响一个或多个工作负载的延迟。

* * 同步 SnapMirror*
+
表示在 SnapMirror 同步关系中将用户数据从主卷复制到二级卷所涉及的集群软件组件。如果同步 SnapMirror 组件处于争用状态，则表示 SnapMirror 同步操作的活动正在影响一个或多个工作负载的延迟。


