---
permalink: performance-checker/concept_understand_events_from_adaptive_qos_policies.html 
sidebar: sidebar 
keywords: understand, events, adaptive, qos, policies, defined, block, size 
summary: 自适应 QoS 策略组会根据卷大小自动扩展吞吐量上限或下限，从而在卷大小发生变化时保持 IOPS 与 TB 的比率。从 ONTAP 9.5 开始，您可以在 QoS 策略中指定块大小，以便同时有效地应用 MB/ 秒阈值。 
---
= 了解已定义块大小的自适应 QoS 策略中的事件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
自适应 QoS 策略组会根据卷大小自动扩展吞吐量上限或下限，从而在卷大小发生变化时保持 IOPS 与 TB 的比率。从 ONTAP 9.5 开始，您可以在 QoS 策略中指定块大小，以便同时有效地应用 MB/ 秒阈值。

在自适应 QoS 策略中分配 IOPS 阈值仅会限制每个工作负载中发生的操作数。根据生成工作负载的客户端上设置的块大小，某些 IOPS 会包含更多数据，因此会给处理操作的节点带来更大的负担。

工作负载的 MB/ 秒值是使用以下公式生成的：

[listing]
----
MB/s = (IOPS * Block Size) / 1000
----
如果工作负载的 IOPS 平均为 3 ， 000 次，而客户端上的块大小设置为 32 KB ，则此工作负载的有效 MB/ 秒为 96 。如果同一工作负载的 IOPS 平均为 3 ， 000 次，而客户端上的块大小设置为 48 KB ，则此工作负载的有效 MB/ 秒为 144 。您可以看到，如果块大小较大，则节点正在处理更多 50% 的数据。

下面，我们来了解一下定义了块大小的以下自适应 QoS 策略，以及如何根据客户端上设置的块大小触发事件。

创建一个策略并将峰值吞吐量设置为 2 ， 500 IOPS/TB ，块大小为 32 KB 。对于已用容量为 1 TB 的卷，此操作会将 MB/ 秒阈值有效地设置为 80 MB/ 秒（（ 2500 IOPS * 32 KB ） /1000 ）。请注意，如果吞吐量值比定义的阈值低 10% ，则 Unified Manager 将生成警告事件。在以下情况下会生成事件：

|===
| Used capacity 2+| 吞吐量超过此数量时生成事件 ... 


|  | IOPS | MB/s 


 a| 
1 TB
 a| 
2 ， 250 次 IOPS
 a| 
72 MB/s



 a| 
2 TB
 a| 
4 ， 500 次 IOPS
 a| 
144 MB/s



 a| 
5 TB
 a| 
11 ， 250 次 IOPS
 a| 
360 MB/s

|===
如果卷正在使用 2 TB 的可用空间，并且 IOPS 为 4 ， 000 ，并且客户端上的 QoS 块大小设置为 32 KB ，则 MB/ 秒吞吐量为 128 MB/ 秒（（ 4 ， 000 IOPS * 32 KB ） / 1000 ）。在此情况下不会生成任何事件，因为对于使用 2 TB 空间的卷， 4 ， 000 次 IOPS 和 128 MB/ 秒均低于阈值。

如果卷正在使用 2 TB 的可用空间，并且 IOPS 为 4 ， 000 ，并且客户端上的 QoS 块大小设置为 64 KB ，则 MB/ 秒吞吐量为 256 MB/ 秒（（（ 4 ， 000 IOPS * 64 KB ） / 1000 ）。在这种情况下， 4 ， 000 次 IOPS 不会生成事件，但 256 MB/ 秒的 MB/ 秒值高于 144 MB/ 秒的阈值，因此会生成事件。

因此，如果因违反包含块大小的自适应 QoS 策略的 MB/ 秒而触发事件，则会在事件详细信息页面的系统诊断部分显示 MB/ 秒图表。如果因违反自适应 QoS 策略的 IOPS 而触发事件，则系统诊断部分会显示一个 IOPS 图表。如果同时违反 IOPS 和 MB/ 秒，您将收到两个事件。

有关调整QoS设置的详细信息、请参见 https://docs.netapp.com/us-en/ontap/performance-admin/index.html["性能管理概述"]。
