---
permalink: performance-checker/concept_what_expected_range_of_performance_is.html 
sidebar: sidebar 
keywords: expected, range, performance, latency, forecast, formed 
summary: 延迟预测是对特定时间的性能上限和下限值的预测。对于工作负载延迟，上限值构成性能阈值。当实际值超过性能阈值时， Unified Manager 将触发动态性能事件。 
---
= 什么是预期性能范围
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
延迟预测是对特定时间的性能上限和下限值的预测。对于工作负载延迟，上限值构成性能阈值。当实际值超过性能阈值时， Unified Manager 将触发动态性能事件。

例如，在上午 9 ： 00 之间的正常工作时间下午 5 ： 00 ，大多数员工可能会在上午 9 ： 00 之间查看他们的电子邮件和上午 10 ： 30对电子邮件服务器的需求增加意味着在此期间后端存储上的工作负载活动会增加。员工可能会注意到电子邮件客户端的响应速度较慢。

中午 12 ： 00 至中午 12 ： 00 之间的午餐时间和下午 1 ： 00在下午 5 ： 00 之后的工作日结束时，大多数员工很可能会离开计算机。对电子邮件服务器的需求通常会减少，同时也会降低对后端存储的需求。或者，也可以在下午 5 ： 00 后开始计划工作负载操作，例如存储备份或病毒扫描并增加后端存储上的活动。

在几天内，工作负载活动的增加和减少决定了活动的预期范围（延迟预测），工作负载的上限和下限。如果某个对象的实际工作负载活动超出上限或下限，并且在一段时间内保持在边界之外，则可能表示该对象已过度使用或未充分使用。



== 如何形成延迟预测

Unified Manager 必须至少收集 3 天的工作负载活动，然后才能开始分析并在图形用户界面中显示 I/O 响应时间的延迟预测。所需的最低数据收集量不会考虑工作负载活动所发生的所有更改。在收集前 3 天的活动后， Unified Manager 将每 24 小时在午夜 12 ： 00 调整一次延迟预测以反映工作负载活动的变化并建立更准确的动态性能阈值。

[NOTE]
====
夏令时（ DST ）会更改系统时间，从而更改受监控工作负载的性能统计信息的延迟预测。Unified Manager 会立即开始更正延迟预测，大约需要 15 天才能完成。在此期间，您可以继续使用 Unified Manager ，但由于 Unified Manager 使用延迟预测来检测动态事件，因此某些事件可能不准确。更改时间之前检测到的事件不受影响。

====