---
permalink: performance-checker/reference_types_of_system_defined_performance_threshold_policies.html 
sidebar: sidebar 
keywords: system-defined, performance, threshold, policies, cluster, node. aggregate, qos 
summary: Unified Manager 提供了一些标准阈值策略，用于监控集群性能并自动生成事件。默认情况下，这些策略处于启用状态，如果违反监控的性能阈值，它们将生成警告或信息事件。 
---
= 系统定义的性能阈值策略的类型
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager 提供了一些标准阈值策略，用于监控集群性能并自动生成事件。默认情况下，这些策略处于启用状态，如果违反监控的性能阈值，它们将生成警告或信息事件。

[NOTE]
====
Cloud Volumes ONTAP ， ONTAP Edge 或 ONTAP Select 系统上未启用系统定义的性能阈值策略。

====
如果您从任何系统定义的性能阈值策略收到不必要的事件，则可以从事件设置页面禁用各个策略的事件。



== 集群阈值策略

默认情况下，系统定义的集群性能阈值策略会分配给 Unified Manager 监控的每个集群：

* * 集群负载不平衡 *
+
确定一个节点的运行负载远高于集群中其他节点，从而可能影响工作负载延迟的情况。

+
为此、它会比较集群中所有节点的已用性能容量值、以查看是否有任何节点超过30%阈值超过24小时。这是一个警告事件。

* * 集群容量不平衡 *
+
确定一个聚合的已用容量远远高于集群中的其他聚合，从而可能影响操作所需的空间的情况。

+
为此，它会比较集群中所有聚合的已用容量值，以确定任何聚合之间是否存在 70% 的差异。这是一个警告事件。





== 节点阈值策略

默认情况下，系统定义的节点性能阈值策略会分配给 Unified Manager 所监控集群中的每个节点：

* * 已违反已用性能容量阈值 *
+
确定单个节点运行超过其运行效率上限从而可能影响工作负载延迟的情况。

+
为此，它会查找使用 100% 以上性能容量且持续 12 小时以上的节点。这是一个警告事件。

* * 节点 HA 对已过度利用 *
+
确定 HA 对中的节点在超出 HA 对操作效率限制的情况。

+
为此，它会查看 HA 对中两个节点的已用性能容量值。如果这两个节点的总已用性能容量超过 200% 且持续 12 小时以上，则控制器故障转移将影响工作负载延迟。这是一个信息性事件。

* * 节点磁盘碎片化 *
+
确定聚合中的一个或多个磁盘碎片化，从而降低关键系统服务的速度并可能影响节点上的工作负载延迟的情况。

+
为此，它会查看节点上所有聚合的特定读写操作比率。在 SyncMirror 重新同步期间或在磁盘擦除操作期间发现错误时，也可能会触发此策略。这是一个警告事件。

+
[NOTE]
====
"`节点磁盘碎片` " 策略仅分析纯 HDD 聚合；不分析 Flash Pool ， SSD 和 FabricPool 聚合。

====




== 聚合阈值策略

默认情况下，系统定义的聚合性能阈值策略会分配给 Unified Manager 所监控集群中的每个聚合：

* * 聚合磁盘过度利用 *
+
确定聚合运行超过其运行效率限制从而可能影响工作负载延迟的情况。它通过查找聚合中磁盘利用率超过 95% 且持续 30 分钟以上的聚合来确定这些情况。然后，此多条件策略将执行以下分析，以帮助确定问题描述的发生原因：

+
** 聚合中的磁盘当前是否正在进行后台维护活动？
+
磁盘可能正在进行的一些后台维护活动包括磁盘重建，磁盘擦除， SyncMirror 重新同步和重新解析。

** 磁盘架光纤通道互连是否存在通信瓶颈？
** 聚合中的可用空间是否太少？只有当三个从属策略中的一个（或多个）也被视为违反时，才会为此策略发出警告事件。如果只有聚合中的磁盘利用率超过 95% ，则不会触发性能事件。




[NOTE]
====
"`聚合磁盘过度利用` " 策略可分析纯 HDD 聚合和 Flash Pool （混合）聚合；不会分析 SSD 和 FabricPool 聚合。

====


== 工作负载延迟阈值策略

系统定义的工作负载延迟阈值策略将分配给已配置性能服务级别策略且定义了 "`expected latency` " 值的任何工作负载：

* 已违反性能服务级别 * 定义的 * 工作负载卷 /LUN 延迟阈值
+
确定已超过 "`预期延迟` " 限制且影响工作负载性能的卷（文件共享）和 LUN 。这是一个警告事件。

+
为此，它会查找前一小时 30% 时间内超过预期延迟值的工作负载。





== QoS 阈值策略

系统定义的 QoS 性能阈值策略将分配给已配置 ONTAP QoS 最大吞吐量策略（ IOPS ， IOPS/TB 或 MB/ 秒）的任何工作负载。当工作负载吞吐量值比配置的 QoS 值低 15% 时， Unified Manager 将触发事件：

* * QoS 最大 IOPS 或 MB/ 秒阈值 *
+
确定已超过其 QoS 最大 IOPS 或 MB/ 秒吞吐量限制且影响工作负载延迟的卷和 LUN 。这是一个警告事件。

+
将单个工作负载分配给策略组后，它会查找在前一小时的每个收集期间内超过分配的 QoS 策略组中定义的最大吞吐量阈值的工作负载。

+
如果多个工作负载共享一个 QoS 策略，则可以通过在策略中添加所有工作负载的 IOPS 或 MB/ 秒并根据阈值检查该总数来实现此目的。

* 具有块大小阈值的 * QoS 峰值 IOPS/TB 或 IOPS/TB *
+
确定已超过自适应 QoS 峰值 IOPS/TB 吞吐量限制（或具有块大小限制的 IOPS/TB ）且正在影响工作负载延迟的卷。这是一个警告事件。

+
为此，它会根据每个卷的大小将自适应 QoS 策略中定义的峰值 IOPS/TB 阈值转换为 QoS 最大 IOPS 值，然后查找在前一小时的每个性能收集期间超过 QoS 最大 IOPS 的卷。

+
[NOTE]
====
只有当集群安装了 ONTAP 9.3 及更高版本的软件时，此策略才会应用于卷。

====
+
在自适应 QoS 策略中定义 "`block size` " 元素后，此阈值将根据每个卷的大小转换为 QoS 最大 MB/ 秒值。然后，它会查找在前一小时的每个性能收集期间超过 QoS 最大 MB/ 秒的卷。

+
[NOTE]
====
只有当集群安装了 ONTAP 9.5 及更高版本的软件时，此策略才会应用于卷。

====

