---
permalink: performance-checker/task_respond_to_cluster_imbalance_performance_events.html 
sidebar: sidebar 
keywords: cluster, imbalance, performance, events 
summary: 如果集群中的一个节点的负载远远高于其他节点，因此可能会影响工作负载延迟，则 Unified Manager 将生成集群不平衡警告事件。通过这些系统定义的事件，可以在许多工作负载受到延迟影响之前更正潜在的性能问题。 
---
= 响应集群不平衡性能事件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果集群中的一个节点的负载远远高于其他节点，因此可能会影响工作负载延迟，则 Unified Manager 将生成集群不平衡警告事件。通过这些系统定义的事件，可以在许多工作负载受到延迟影响之前更正潜在的性能问题。

* 您需要的内容 *

您必须具有操作员，应用程序管理员或存储管理员角色。

Unified Manager 通过比较集群中所有节点的已用性能容量值来查看任何节点之间是否存在 30% 的负载差异，从而针对集群不平衡阈值策略违规生成警告事件。

以下步骤可帮助您确定以下资源，以便将高性能工作负载移动到利用率较低的节点：

* 同一集群上利用率较低的节点
* 新节点上利用率最低的聚合
* 当前节点上性能最高的卷


.步骤
. 显示 * 事件 * 详细信息页面以查看有关事件的信息。
. 查看 * 问题描述 * ，其中介绍了导致事件的违反阈值的情况。
+
例如，消息 "`the performance capacity used counter indicates a load difference of 62% between the nodes on cluster Dallas-1-8 and has triggered a warning event based on the system threshold of 30%` " 指示其中一个节点上的性能容量已被过度使用并影响节点性能。

. 查看 * 建议操作 * 中的文本，将高性能卷从已用性能容量值较高的节点移动到已用性能容量值最低的节点。
. 确定已用性能容量值最高和最低的节点：
+
.. 在 * 事件信息 * 部分中，单击源集群的名称。
.. 在 * 集群 / 性能摘要 * 页面中，单击 * 受管对象 * 区域中的 * 节点 * 。
.. 在 * 节点 * 清单页面中，按 * 已用性能容量 * 列对节点进行排序。
.. 确定已用性能容量值最高和最低的节点，并记下这些名称。


. 确定已用性能容量值最高的节点上使用的 IOPS 最多的卷：
+
.. 单击已用性能容量值最高的节点。
.. 在 * 节点 / 性能资源管理器 * 页面中，从 * 查看和比较 * 菜单中选择 * 此节点上的聚合 * 。
.. 单击已用性能容量值最高的聚合。
.. 在 * 聚合 / 性能资源管理器 * 页面中，从 * 查看和比较 * 菜单中选择 * 此聚合上的卷 * 。
.. 按 * IOPS * 列对卷进行排序，并记下 IOPS 最多的卷的名称以及卷所在聚合的名称。


. 确定已用性能容量值最低的节点上利用率最低的聚合：
+
.. 单击 * 存储 * > * 聚合 * 以显示 * 聚合 * 清单页面。
.. 选择 * 性能：所有聚合 * 视图。
.. 单击 * 筛选器 * 按钮并添加一个筛选器，其中 "`Node` " 等于您在步骤 4 中记下的已用性能容量值最低的节点的名称。
.. 记下已用性能容量值最低的聚合的名称。


. 将卷从过载节点移至新节点上已确定利用率较低的聚合。
+
您可以使用 ONTAP System Manager ， OnCommand Workflow Automation ， ONTAP 命令或这些工具的组合来执行移动操作。



几天后，检查是否从此集群收到相同的集群不平衡事件。
