---
permalink: storage-mgmt/concept_manage_storage_efficiency_policies.html 
sidebar: sidebar 
keywords: manage, storage, efficiency, policies, guidelines, create, custom 
summary: 通过存储效率策略（ Storage Efficiency Policy ， SEP ），您可以定义工作负载的存储效率特征。您可以在最初创建工作负载时为工作负载分配 SEP ，也可以稍后通过编辑工作负载来分配 SEP 。 
---
= 管理存储效率策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过存储效率策略（ Storage Efficiency Policy ， SEP ），您可以定义工作负载的存储效率特征。您可以在最初创建工作负载时为工作负载分配 SEP ，也可以稍后通过编辑工作负载来分配 SEP 。

存储效率包括使用精简配置，重复数据删除和数据压缩等技术来提高存储利用率并降低存储成本。创建 SEP 时，您可以单独使用这些节省空间的技术，也可以同时使用这些技术来实现最高的存储效率。将策略与存储工作负载关联后，系统会为其分配指定的策略设置。通过 Unified Manager ，您可以分配系统定义的和用户定义的 SE ，以优化数据中心中的存储资源。

Unified Manager 提供了两个系统定义的 SEP ：高和低。这些 SEP 适用于数据中心中的大多数存储工作负载，但是，如果系统定义的 SEP 不符合您的要求，您可以创建自己的策略。

您不能修改系统定义的 SEP 或当前分配给工作负载的 SEP 。您不能删除分配给工作负载的 SEP ，也不能删除唯一可用的 SEP 。

存储效率策略页面列出了可用的 SEP ，并可用于添加，编辑和删除自定义的 SEP 。此页面显示以下信息：

|===
| 字段 | Description 


 a| 
Name
 a| 
SEP 的名称。



 a| 
Type
 a| 
策略是系统定义的还是用户定义的。



 a| 
空间预留
 a| 
卷是精简配置卷还是厚配置卷。



 a| 
重复数据删除
 a| 
是否在工作负载上启用重复数据删除：

* 实时：在工作负载上写入数据时进行重复数据删除
* 后台：重复数据删除在工作负载中进行
* disable ：已对工作负载禁用重复数据删除




 a| 
压缩
 a| 
是否在工作负载上启用数据压缩：

* 实时：在工作负载上写入数据时进行数据压缩
* Background ：数据压缩在工作负载中进行
* disable ：已对工作负载禁用数据压缩




 a| 
工作负载
 a| 
已分配 SEP 的存储工作负载数量

|===


== 创建自定义存储效率策略的准则

如果现有 SEP 不满足存储工作负载的策略要求，您可以创建自定义 SEP 。但是，建议您尝试对存储工作负载使用系统定义的 SEP ，并且仅在必要时创建自定义 SEP 。

您可以在所有工作负载页面和卷 / 运行状况详细信息页面中查看分配给工作负载的 SEP 。您可以在信息板上的容量面板和容量：所有集群视图中根据这些存储效率查看集群级别的数据精简率。
