---
permalink: storage-mgmt/concept_workloads_dashboard.html 
sidebar: sidebar 
keywords: workloads, overview, data center, sections 
summary: 工作负载表示卷或 LUN 等存储对象的输入 / 输出（ I/O ）操作。存储的配置方式取决于预期的工作负载要求。只有在存储对象之间存在流量时， Active IQ Unified Manager 才会跟踪工作负载统计信息。例如，在用户开始使用数据库或电子邮件应用程序后，可以使用工作负载 IOPS 和延迟值。 
---
= 工作负载概述
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
工作负载表示卷或 LUN 等存储对象的输入 / 输出（ I/O ）操作。存储的配置方式取决于预期的工作负载要求。只有在存储对象之间存在流量时， Active IQ Unified Manager 才会跟踪工作负载统计信息。例如，在用户开始使用数据库或电子邮件应用程序后，可以使用工作负载 IOPS 和延迟值。

工作负载页面显示了 Unified Manager 管理的 ONTAP 集群的存储工作负载摘要。它提供了有关符合性能服务级别的存储工作负载以及不符合性能服务级别的存储工作负载的累积概览信息。此外，您还可以通过它评估整个数据中心内集群的总容量和性能，可用容量和性能以及已用容量和性能（ IOPS ）。

[NOTE]
====
建议您评估不合规，不可用或不受任何性能服务级别管理的存储工作负载的数量，并采取必要措施以确保其合规性，容量使用情况和 IOPS 。

====
工作负载页面包含以下两个部分：

* 工作负载概述：概述 Unified Manager 管理的 ONTAP 集群上的存储工作负载数量。
* 数据中心概述：概述数据中心存储工作负载的容量和 IOPS 。相关数据将显示在数据中心级别以及各个级别。




== 工作负载概述部分

工作负载概述部分提供了存储工作负载的累积概览信息。存储工作负载的状态将根据已分配和未分配的性能服务级别显示。

* * 已分配 * ：对于已分配性能服务级别的存储工作负载，系统会报告以下状态：
+
** * 符合 * ：存储工作负载的性能取决于分配给它们的性能服务级别。如果存储工作负载处于关联性能服务级别中定义的阈值延迟范围内，则这些工作负载将标记为 "`遵从` " 。符合要求的工作负载将标记为蓝色。
** * 不符合 * ：在性能监控期间，如果存储工作负载延迟超过关联性能服务级别中定义的阈值延迟，则存储工作负载将标记为 "`不符合` " 。不符合要求的工作负载将标记为橙色。
** * 不可用 * ：如果存储工作负载处于脱机状态或无法访问相应集群，则这些存储工作负载将标记为 "`不可用` " 。不可用的工作负载将标记为红色。


* * 未分配 * ：未分配性能服务级别的存储工作负载报告为 "`未分配` " 。此数字由信息图标表示。


工作负载总数是已分配和未分配工作负载的总和。

您可以单击此部分中显示的工作负载总数，然后在工作负载页面上查看这些工作负载。

" 按性能服务级别划分的遵从性 " 子部分显示可用存储工作负载的总数：

* 符合每种类型的性能服务级别
* 分配的性能服务级别与建议的性能服务级别不匹配




== 数据中心概述部分

数据中心概述部分以图形方式表示数据中心中所有集群的可用容量和已用容量以及 IOPS 。通过使用此数据，您应管理存储工作负载的容量和 IOPS 。此外，此部分还会显示所有集群中存储工作负载的以下信息：

* 数据中心中所有集群的总容量，可用容量和已用容量
* 数据中心中所有集群的总 IOPS ，可用 IOPS 和已用 IOPS
* 基于每个性能服务级别的可用容量和已用容量
* 基于每个性能服务级别的可用和已用 IOPS
* 未分配性能服务级别的工作负载使用的总空间和 IOPS


* 如何根据性能服务级别计算数据中心容量和性能 *

已用容量和 IOPS 是根据集群中所有存储工作负载的总已用容量和性能进行检索的。

可用 IOPS 是根据节点上的预期延迟和建议性能服务级别计算得出的。它包括预期延迟小于或等于自身预期延迟的所有性能服务级别的可用 IOPS 。

可用容量是根据聚合上的预期延迟和建议性能服务级别计算得出的。它包括预期延迟小于或等于自身预期延迟的所有性能服务级别的可用容量。
