---
permalink: storage-mgmt/concept_monitor_vms.html 
sidebar: sidebar 
keywords: monitor, virtual, machines, view, summary, topology, expand 
summary: 对于虚拟机（ VM ）应用程序上的任何延迟问题描述，您可能需要监控 VM 以分析发生原因并对其进行故障排除。将 VM 的 vCenter Server 和托管 VM 存储的 ONTAP 集群添加到 Unified Manager 后，这些 VM 将可用。 
---
= 监控虚拟机
:icons: font
:imagesdir: ../media/


[role="lead"]
对于虚拟机（ VM ）应用程序上的任何延迟问题描述，您可能需要监控 VM 以分析发生原因并对其进行故障排除。将 VM 的 vCenter Server 和托管 VM 存储的 ONTAP 集群添加到 Unified Manager 后，这些 VM 将可用。

您可以在 "* VMware* ">" * 虚拟机 * " 页面上查看虚拟机的详细信息。此时将显示可用性，状态，已用容量和已分配容量，网络延迟以及虚拟机，数据存储库和主机的 IOPS 和延迟等信息。对于支持多个数据存储库的 VM ，网格将显示延迟最差的数据存储库的指标，并显示一个星号图标（ * ），表示其他数据存储库。如果单击此图标，则会显示其他数据存储库的指标。其中某些列不可用于排序和筛选。

[NOTE]
====
要查看虚拟机及其详细信息，必须完成对 ONTAP 集群的发现（轮询或指标收集）。如果从 Unified Manager 中删除集群，则在下一个发现周期之后，虚拟机将不再可用。

====
在此页面中，您还可以查看虚拟机的详细拓扑，其中显示了与虚拟机相关的组件，例如与其连接的主机，虚拟磁盘和数据存储库。拓扑视图按以下顺序显示其特定层中的底层组件： * 虚拟磁盘 * > * 虚拟机 * > * 主机 * > * 网络 * > * 数据存储库 * > * VMDK* 。

您可以从拓扑角度确定 I/O 路径和组件级别延迟，并确定存储是否为性能问题描述的发生原因。此拓扑的摘要视图会显示 I/O 路径，并突出显示存在 IOPS 和延迟问题的组件，以供您确定故障排除步骤。此外，您还可以通过扩展拓扑视图单独描述每个组件以及该组件的延迟。您可以选择一个组件来确定通过层突出显示的 I/O 路径。



== 查看摘要拓扑

要通过查看摘要拓扑中的虚拟机来确定性能问题，请执行以下操作：

. 转至 * VMware * > * 虚拟机 * 。
. 通过在搜索框中键入虚拟机名称来搜索虚拟机。您也可以单击 * 筛选器 * 按钮，根据特定条件筛选搜索结果。但是，如果找不到虚拟机，请确保已添加并发现相应的 vCenter Server 。
+
[NOTE]
====
vCenter Server 允许使用特殊字符（例如 % ， & ， * ， $ ， # ， @ ，！， \ ， / ，：， * ，？， "` ， < ， > ， 在 vSphere 实体的名称中，例如 VM ，集群，数据存储库，文件夹， 或文件。VMware vCenter Server 和 ESX/ESXi Server 不会转义显示名称中使用的特殊字符。但是，在 Unified Manager 中处理此名称时，此名称的显示方式会有所不同。例如，在 Unified Manager 中， vCenter Server 中名为 ` %$VC_AIQUM_clone_191124%` 的 VM 显示为 ` %25$VC_AIQUM_clone_191124%25` 。在查询名称包含特殊字符的虚拟机时，必须记下此问题描述。

====
. 检查虚拟机的状态。虚拟机状态从 vCenter Server 中检索。可以使用以下状态。有关这些状态的详细信息，请参见 VMware 文档。
+
** 正常
** 警告
** 警报
** 不受监控
** 未知


. 单击虚拟机旁边的向下箭头可查看计算层，网络层和存储层中各个组件的拓扑摘要视图。此时将突出显示存在延迟问题的节点。摘要视图显示组件的最差延迟。例如，如果一个虚拟机具有多个虚拟磁盘，则此视图将显示所有虚拟磁盘中延迟最差的虚拟磁盘。
. 要分析数据存储库在一段时间内的延迟和吞吐量，请单击数据存储库对象图标顶部的 * 工作负载分析器 * 按钮。您可以转到工作负载分析页面，在此可以选择时间范围并查看数据存储库的性能图表。有关工作负载分析器的详细信息，请参见 _Troubleshooting Workloads Using the Workload analyzer 。




== 查看扩展拓扑

您可以通过查看虚拟机的扩展拓扑来单独深入查看每个组件。

.步骤
. 在摘要拓扑视图中，单击 * 扩展拓扑 * 。您可以单独查看每个组件的详细拓扑以及每个对象的延迟数。如果一个类别中有多个节点，例如数据存储库或 VMDK 中的多个节点，则延迟最差的节点将以红色突出显示。
. 要检查特定对象的 IO 路径，请单击该对象以查看 IO 路径以及相应的映射。例如，要查看虚拟磁盘的映射，请单击该虚拟磁盘以查看其与相应 VMDK 的突出显示映射。如果这些组件的性能滞后，您可以从 ONTAP 收集更多数据并对问题描述进行故障排除。
+
[NOTE]
====
不会报告 VMDK 的指标。在拓扑中，仅显示 VMDK 名称，而不显示指标。

====


* 相关信息 *

link:../performance-checker/concept_troubleshooting_workloads_using_workload_analyzer.html["使用工作负载分析器对工作负载进行故障排除"]
