---
permalink: storage-mgmt/concept_assign_policies_on_workloads.html 
sidebar: sidebar 
keywords: assign, policies, workloads, single, multiple, storage, system-recommended, psls 
summary: 您可以使用不同的导航选项从所有工作负载页面为存储工作负载分配存储效率策略（ Storage Efficiency Policy ， SEP ）和性能服务级别（ Performance Service Levels ， PSL ）。 
---
= 为工作负载分配策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用不同的导航选项从所有工作负载页面为存储工作负载分配存储效率策略（ Storage Efficiency Policy ， SEP ）和性能服务级别（ Performance Service Levels ， PSL ）。



== 为单个工作负载分配策略

您可以为单个工作负载分配 PSL 或 SEP ，也可以同时分配这两者。请按照以下步骤操作：

. 选择工作负载。
. 单击该行旁边的编辑图标，然后单击 * 编辑 * 。
+
已启用 * 已分配性能服务级别 * 和 * 存储效率策略 * 字段。

. 选择所需的 PSL 或 SEP ，或者同时选择这两者。
. 单击复选图标以应用更改。


[NOTE]
====
您也可以选择工作负载并单击 * 更多操作 * 来分配策略。

====


== 为多个存储工作负载分配策略

您可以将一个 PSL 或一个 SEP 同时分配给多个存储工作负载。请按照以下步骤操作：

. 选中要将策略分配到的工作负载对应的复选框，或者选择数据中心中的所有工作负载。
. 单击 * 更多操作 * 。
. 要分配 PSL ，请选择 * 分配性能服务级别 * 。要分配 SEP ，请选择 * 分配存储效率策略 * 。此时将显示一个弹出窗口，供您选择策略。
. 选择相应的策略并单击 * 应用 * 。此时将显示分配策略的工作负载数量。此外，还会列出未分配策略的工作负载以及发生原因。
+
[NOTE]
====
根据选定的工作负载数量，批量对工作负载应用策略可能需要一段时间。当操作在后台运行时，您可以单击 * 在后台运行 * 按钮并继续执行其他任务。批量分配完成后，您可以查看完成状态。如果要对多个工作负载应用 PSL ，则在运行上一个批量分配作业时，不能触发另一个请求。

====




== 为工作负载分配系统建议的 PSL

您可以将系统建议的 PSL 分配给数据中心中未分配 PSL 的存储工作负载，或者分配的 PSL 与系统建议不匹配。要使用此功能，请单击 * 分配系统建议 PSL* 按钮。您无需选择特定工作负载。

此建议由系统分析在内部确定，对于 IOPS 和其他参数与任何可用 PSL 的定义不一致的工作负载，此建议将跳过。此外， `Waiting for I/O` 和 Learning 状态的存储工作负载也不包括在内。

[NOTE]
====
Unified Manager 会在工作负载名称中查找一些特殊关键字来覆盖系统分析并为工作负载建议其他 PSL 。如果工作负载的名称中包含字母 "`ora` " ，则建议使用 "* 至高性能 * PSL" 。如果工作负载的名称中包含字母 "`VM` " ，则建议使用 "* 性能 "* PSL" 。

====
另请参见知识库(KB)文章 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/Active_IQ_Unified_Manager/Performance_Service_Level'_is_not_adaptive_to_a_highly_variable_workload["ActiveIQ UM"分配系统建议的性能服务级别"无法适应高度可变的工作负载"]
