---
permalink: storage-mgmt/concept_what_options_do_i_have_in_fix_it_button.html 
sidebar: sidebar 
keywords: fix it,fix all 
summary: '" 管理操作 " 页面为您提供了 " 修复 " 或 " 全部修复 " 按钮，用于修复 Unified Manager 通过事件收到通知的问题。' 
---
= 看到 " 修复 " 或 " 全部修复 " 按钮时，我有哪些选项
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
" 管理操作 " 页面提供了 * 修复它 * 或 * 全部修复 * 按钮，用于修复 Unified Manager 通过事件收到通知的问题。

我们建议您根据需要单击按钮以修复问题描述。但是，如果您不确定是否要按照 Unified Manager 的建议解析问题描述，则可以执行以下操作：

|===
| 您希望执行什么操作？ | * 操作 * 


 a| 
让 Unified Manager 修复所有已标识对象上的问题描述。
 a| 
单击 * 全部修复 * 按钮。



 a| 
此时，请勿修复任何已标识对象的问题描述，并隐藏此管理操作，直到事件再次引发为止。
 a| 
单击向下箭头，然后单击 * 全部取消 * 。



 a| 
仅修复某些已标识对象上的问题描述。
 a| 
单击管理操作的名称以展开列表并显示所有单独的 * 修复它 * 操作。然后按照步骤修复或取消单个管理操作。

|===
|===
| 您希望执行什么操作？ | Action 


 a| 
让 Unified Manager 修复问题描述。
 a| 
单击 * 修复它 * 按钮。



 a| 
此时请勿修复问题描述并隐藏此管理操作，直到事件再次引发为止。
 a| 
单击向下箭头，然后单击 * 取消 * 。



 a| 
显示此事件的详细信息，以便更好地了解问题描述。
 a| 
* 单击 * 修复它 * 按钮，然后查看将在显示的对话框中应用的修复。
* 单击向下箭头并单击 * 查看事件详细信息 * 以显示事件详细信息页面。


如果要修复问题描述，请从上述任一页面中单击 * 修复它 * 。



 a| 
显示此存储对象的详细信息，以便更好地了解问题描述。
 a| 
单击存储对象的名称以在性能资源管理器或运行状况详细信息页面中显示详细信息。

|===
在某些情况下，此修复会反映在下一个 15 分钟的配置轮询中。在其他情况下，可能需要长达数小时才能验证配置更改并废弃事件。

要查看已完成或正在进行的管理操作列表，请单击筛选器图标并选择 * 已完成 * 或 * 正在进行 * 。

请修复以串行方式运行的所有操作，以便在查看 * 进行中 * 面板时，某些对象的状态为 * 进行中 * ，而其他对象的状态为 * 已计划 * ，这意味着它们仍在等待实施。
