---
permalink: storage-mgmt/concept_manage_performance_service_levels.html 
sidebar: sidebar 
keywords: manage, performance, service, levels 
summary: 通过性能服务级别，您可以定义工作负载的性能和存储目标。您可以在最初创建工作负载时为工作负载分配性能服务级别，也可以稍后通过编辑工作负载来分配性能服务级别。 
---
= 管理性能服务级别
:icons: font
:imagesdir: ../media/


[role="lead"]
通过性能服务级别，您可以定义工作负载的性能和存储目标。您可以在最初创建工作负载时为工作负载分配性能服务级别，也可以稍后通过编辑工作负载来分配性能服务级别。

存储资源的管理和监控基于服务级别目标（ Service Level Objective ， SLO ）。SLO 由基于所需性能和容量的服务级别协议定义。在 Unified Manager 中， SLO 是指在 NetApp 存储上运行的应用程序的 PSL 定义。存储服务会根据底层资源的性能和利用率进行区分。PSL 是存储服务目标的问题描述。通过 PSL ，存储提供程序可以为工作负载指定性能和容量目标。

Unified Manager 提供了一些无法更改的预设策略。这些预定义的性能服务级别包括： " 至高性能 " ， " 性能 " 和 " 价值 " 。极高性能，性能和价值 PSL 适用于数据中心中的大多数常见存储工作负载。Unified Manager 还为数据库应用程序提供了三个 PSL ：适用于数据库日志的至高 PSL ，适用于数据库共享数据的至高 PSL 以及适用于数据库数据的至高 PSL 。这些是性能极高的 PSL ，支持突发 IOPS ，适用于吞吐量需求最高的数据库应用程序。如果这些预定义的 PSL 不符合您的要求，则可以根据您的需求创建新的 PSL 。

您可以从 * 策略 * > * 性能服务级别 * 页面以及使用存储提供程序 API 访问 PSL 。通过为存储工作负载分配 PSL 来管理存储工作负载非常方便，因为您不必单独管理存储工作负载。也可以通过重新分配另一个 PSL 来管理任何修改，而不是单独管理这些修改。

您不能修改系统定义的 PSL 或当前分配给工作负载的 PSL 。您不能删除分配给工作负载的 PSL ，也不能删除唯一可用的 PSL 。

" 性能服务级别 " 页面列出了可用的 PSL 策略，并可用于添加，编辑和删除这些策略。此页面显示以下信息：

|===
| 字段 | Description 


 a| 
Name
 a| 
性能服务级别的名称。



 a| 
Type
 a| 
策略是系统定义的还是用户定义的。



 a| 
预期 IOPS
 a| 
应用程序应在 LUN 或文件共享上执行的最小 IOPS 数。预期 IOPS 用于根据存储对象分配的大小指定最小预期分配的 IOPS 。



 a| 
峰值 IOPS
 a| 
应用程序可以对 LUN 或文件共享执行的最大 IOPS 数。峰值 IOPS 用于根据存储对象的已分配大小或存储对象的已用大小指定可能分配的最大 IOPS 。

峰值 IOPS 基于分配策略。分配策略为 allocated-space 或 used-space 。如果将分配策略设置为 allocated-space ，则会根据存储对象的大小计算峰值 IOPS 。如果将分配策略设置为 used-space ，则峰值 IOPS 将根据存储对象中存储的数据量并考虑存储效率进行计算。默认情况下，分配策略设置为 used-space 。



 a| 
绝对最小 IOPS
 a| 
当预期 IOPS 小于此值时，绝对最小 IOPS 将用作覆盖。系统定义的 PSL 的默认值如下：

* 至高性能：如果预期 IOPS >= 6144/TB ，则绝对最小 IOPS = 1000
* 性能：如果预期 IOPS >= 2048/TB 且 < 6144/TB ，则绝对最小 IOPS = 500
* 值：如果预期 IOPS >= 128/TB 且 < 2048/TB ，则绝对最小 IOPS = 75


系统定义的数据库 PSL 的默认值如下：

* 适用于数据库日志的至高性能：如果预期 IOPS >= 22528 ，则绝对最小 IOPS = 4000
* 数据库共享数据的至高性能：如果预期 IOPS >= 16384 ，则绝对最小 IOPS = 2000
* 适用于数据库数据的至高性能：如果预期 IOPS >= 12288 ，则绝对最小 IOPS = 2000


自定义 PSL 的绝对最小 IOPS 值越高，最大值可以为 75000 。较低的值计算如下：

1000/ 预期延迟



 a| 
预期延迟
 a| 
存储 IOPS 的预期延迟，以每操作毫秒数（毫秒 / 操作）为单位。



 a| 
Capacity
 a| 
集群中的总可用容量和已用容量。



 a| 
工作负载
 a| 
已分配 PSL 的存储工作负载数量。

|===
有关峰值 IOPS 和预期 IOPS 如何帮助在 ONTAP 集群上实现一致的差异化性能的信息，请参见以下知识库文章：

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/Active_IQ_Unified_Manager/What_is_Performance_Budgeting%3F["什么是性能预算？"]

请注意，如果工作负载在前一小时 30% 的时间内超过预期延迟值，则 Unified Manager 将生成以下事件之一，以通知您可能存在性能问题描述： " 已违反性能服务级别策略定义的工作负载卷延迟阈值 " 或 " 已违反性能服务级别策略定义的工作负载 LUN 延迟阈值 " 。您可能需要分析工作负载，以查看可能导致延迟值增加的原因。

下表提供了有关系统定义的 PSL 的信息：

|===
| 性能服务级别 | 问题描述和用例 | 预期延迟（毫秒 / 操作） | 峰值 IOPS | 预期 IOPS | 绝对最小 IOPS 


 a| 
极致性能
 a| 
提供极高的吞吐量和极低的延迟

非常适合延迟敏感型应用程序
 a| 
1.
 a| 
12288
 a| 
6144
 a| 
1000



 a| 
性能
 a| 
提供高吞吐量和低延迟

非常适合数据库和虚拟化应用程序
 a| 
2.
 a| 
4096
 a| 
2048
 a| 
500



 a| 
价值
 a| 
提供高存储容量和中等延迟

非常适合高容量应用程序，例如电子邮件， Web 内容，文件共享和备份目标
 a| 
17
 a| 
512
 a| 
128.
 a| 
75



 a| 
适用于数据库日志的至高性能
 a| 
以最低延迟提供最大吞吐量。

非常适合支持数据库日志的数据库应用程序。此 PSL 可提供最高的吞吐量，因为数据库日志非常突发，并且日志记录始终是按需的。
 a| 
1.
 a| 
45056
 a| 
22528
 a| 
4000



 a| 
适用于数据库共享数据的至高性能
 a| 
以最低延迟提供极高的吞吐量。

非常适合存储在通用数据存储库中但在数据库之间共享的数据库应用程序数据。
 a| 
1.
 a| 
32768
 a| 
16384
 a| 
2000 年



 a| 
适用于数据库数据的至高性能
 a| 
以最低延迟提供高吞吐量。

非常适合数据库应用程序数据，例如数据库表信息和元数据。
 a| 
1.
 a| 
24576
 a| 
12288
 a| 
2000 年

|===