---
permalink: storage-mgmt/concept_all_workloads.html 
sidebar: sidebar 
keywords: view, workloads, add, provision, storage, filter, analyze, performance, capacity, criteria 
summary: 所有工作负载视图显示数据中心集群上所有可用工作负载的列表。 
---
= 查看工作负载
:icons: font
:imagesdir: ../media/


[role="lead"]
所有工作负载视图显示数据中心集群上所有可用工作负载的列表。

所有工作负载视图会列出与 Unified Manager 管理的 ONTAP 集群关联的存储工作负载。此外，您还可以通过此页面为存储工作负载分配存储效率策略（ Storage Efficiency Policy ， SEP ）和性能服务级别（ Performance Service Levels ， PSL ）。

将集群添加到 Unified Manager 时，系统会自动发现每个集群上的存储工作负载并将其显示在此页面上，但 FlexGroup 卷及其成分卷除外。

只有在对存储工作负载启动 I/O 操作后， Unified Manager 才会开始分析工作负载以获得建议（建议的 PSL ）。对于未执行任何 I/O 操作的新发现的存储工作负载，状态为 "`Waiting for I/O` " 。对存储工作负载执行 I/O 操作后， Unified Manager 将开始分析，工作负载状态将更改为 "`Learning ……` " 。分析完成后（自 I/O 操作开始起 24 小时内），将显示存储工作负载的建议 PSL 。

使用 * 工作负载 * > * 所有工作负载 * 选项，您可以执行多项任务：

* 添加或配置存储工作负载
* 查看和筛选工作负载列表
* 为存储工作负载分配 PSL
* 评估系统建议的 PSL 并将其分配给工作负载
* 为存储工作负载分配 SEP




== 添加或配置存储工作负载

您可以为支持的 LUN （支持 iSCSI 和 FCP 协议）， NFS 文件共享和 SMB 共享添加或配置存储工作负载。



== 查看和筛选工作负载

在所有工作负载屏幕上，您可以查看数据中心中的所有工作负载，或者根据特定存储工作负载的 PSL 或名称搜索这些工作负载。您可以使用筛选器图标输入搜索的特定条件。您可以按不同的筛选条件进行搜索，例如按主机集群或 Storage VM 进行搜索。通过 * 容量总计 * 选项，可以按工作负载的总容量（以 MB 为单位）进行筛选。但是，在这种情况下，返回的工作负载数量可能会有所不同，因为系统会在字节级别比较总容量。

对于每个工作负载，将显示主机集群和 Storage VM 等信息以及分配的 PSL 和 SEP 。

您还可以通过此页面查看工作负载的性能详细信息。您可以通过单击 * 选择 / 排序列 * 按钮并选择要查看的特定列来查看有关工作负载的 IOPS ，容量和延迟的详细信息。" 性能视图 " 列显示工作负载的平均 IOPS 和峰值 IOPS ，您可以单击工作负载分析器图标以查看详细的 IOPS 分析。"IOPS 分析 " 弹出窗口中的 * 分析工作负载 * 按钮将转到 " 工作负载分析 " 页面，在此可以选择一个时间范围并查看选定工作负载的延迟，吞吐量和容量趋势。有关工作负载分析器的详细信息，请参见 _Troubleshooting Workloads Using the Workload analyzer



== 分析工作负载的性能和容量标准

您可以单击 * 性能视图 * 列中的条形图图标来查看有关工作负载的性能信息以帮助进行故障排除。要在 " 工作负载分析 " 页面上查看性能和容量图表以分析对象，请单击 * 分析工作负载 * 按钮。
