---
permalink: storage-mgmt/reference_dashboard_page.html 
sidebar: sidebar 
keywords: dashboard page, 
summary: '信息板页面包含一些 " 面板 " ，用于显示所监控集群的容量，性能和安全运行状况概貌。此页面还提供了一个管理操作面板，其中列出了 Unified Manager 可用来解决某些事件的修复程序。' 
---
= 信息板页面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
" 信息板 " 页面包含 " 面板 " ，用于显示正在监控的集群的容量，性能和安全运行状况概况。此页面还提供了一个管理操作面板，其中列出了 Unified Manager 可用来解决某些事件的修复程序。

大多数面板还会显示该类别中的活动事件数量以及过去 24 小时内添加的新事件数量。此信息有助于您确定可能需要进一步分析哪些集群才能解决事件。单击这些事件将显示排名靠前的事件，并提供指向经过筛选以显示该类别中活动事件的事件管理清单页面的链接。

在信息板顶部，您可以选择这些面板是显示所有受监控集群（ " 所有集群 " ）的信息还是显示单个集群的信息。您可以先查看所有集群的状态，然后在需要查看详细信息时深入查看各个集群。

[NOTE]
====
根据您的配置、信息板上会显示下面列出的某些面板。

====


== 管理操作面板

Unified Manager 可以全面诊断某些问题并提供单一解决方案。如果可用，这些解决方法将显示在此面板中，并显示 * 修复它 * 或 * 全部修复 * 按钮。您可以直接从 Unified Manager 修复这些问题，而不必使用 ONTAP 系统管理器或 ONTAP 命令行界面。要查看所有问题、请单击See link:concept_fix_ontap_issues_directly_from_unified_manager.html["直接从 Unified Manager 修复 ONTAP 问题"] 有关详细信息 ...



== 容量面板

在查看所有集群时，此面板会显示每个集群的已用物理容量（应用存储效率节省后）和物理可用容量（不包括潜在的存储效率节省），预计磁盘达到全满前的天数， 以及基于已配置的 ONTAP 存储效率设置的数据精简率。它还会列出任何已配置云层的已用容量。单击条形图可转到该集群的聚合清单页面。单击 " 达到全满天数 " 文本将显示一条消息，用于标识剩余容量天数最少的聚合；单击聚合名称可查看更多详细信息。

查看单个集群时，此面板会显示按本地层上的每个磁盘类型排序的数据聚合的已用物理容量和物理可用容量，以及云层的已用容量和物理可用容量。单击某个磁盘类型的条形图可转到使用该磁盘类型的卷的卷清单页面。



== 性能容量面板

在查看所有集群时，此面板会显示每个集群的性能容量值（过去 1 小时的平均值）以及性能容量达到上限之前的天数（基于每日增长率）。单击条形图可转到该集群的节点清单页面。请注意，节点清单页面会显示过去 72 小时的平均性能容量。单击 "Days to Full" 文本将显示一条消息，指出剩余性能容量天数最少的节点；单击节点名称可查看更多详细信息。

查看单个集群时，此面板会显示集群已用性能容量百分比，总 IOPS 和总吞吐量（ MB/ 秒）值，以及预计这三个指标中每个指标达到上限之前的天数。



== 工作负载IOPS面板

查看单个集群时，此面板会显示当前在特定 IOPS 范围内运行的工作负载总数，并在将光标悬停在图表上时指示每个磁盘类型的数量。



== 工作负载性能面板

此面板显示分配给每个性能服务级别（ PSL ）策略的遵从和不遵从工作负载总数。它还会显示未分配 PSL 的工作负载数量。单击条形图可转到 " 工作负载 " 页面中分配给该策略的符合性工作负载。单击条形图后面的数字可转到分配给该策略的遵从和不遵从工作负载。



== 安全面板

"安全"面板将根据您的当前视图显示所有集群或单个集群的高级安全状态。此面板将显示：

* 列出过去24小时内收到的安全事件。单击某个事件可在事件详细信息页面上查看详细信息
* 集群安全状态(合规和不合规集群的数量)
* Storage VM安全状态(合规和不合规Storage VM的计数)
* 卷加密状态(已加密或未加密的卷计数)
* 卷反勒索软件状态(启用或禁用了反勒索软件的卷数量)


您可以单击合规和不合规集群、Storage VMS、加密和未加密卷以及卷反勒索软件状态的条形图、转到相应页面并查看筛选后的集群、Storage VM和卷的安全详细信息。

合规性基于 http://www.netapp.com/us/media/tr-4569.pdf["《适用于 ONTAP 9 的 NetApp 安全加固指南》"]。单击面板顶部的右箭头可在安全性页面上查看所有集群的安全详细信息。有关信息，请参见link:..//health-checker/task_view_detailed_security_status_for_clusters_and_svms.html["查看集群和 Storage VM 的详细安全状态"]



== 数据保护面板

此面板显示数据中心中单个或所有集群的数据保护摘要。它会显示过去 24 小时在 ONTAP 中引发的数据保护事件总数和活动事件数。单击每个事件中的链接将转到 " 事件 " 详细信息页面。您可以单击 * 查看全部 * 链接以查看事件管理清单页面中的所有活动保护事件。

此面板还会显示集群中的卷数、或者显示受Snapshot副本和SnapMirror关系保护的数据中心中的所有集群的卷数。对于SnapMirror关系、将考虑源集群上的卷计数。您还可以根据滞后状态查看SnapMirror恢复点目标(RPO)滞后的卷关系数量。您可以将鼠标悬停在此处查看相应的计数和图例。您可以单击：

* 有关未受保护的卷和受Snapshot副本保护的卷的条形图、请转到卷页面并查看详细信息。
* 所有关系的条形图将转到"关系"页面、其中会根据源集群筛选详细信息。


有关详细信息，请参见 link:../data-protection/view-protection-status.html["查看卷保护状态"]。



== 使用情况概述面板

查看所有集群时，您可以选择按最高 IOPS ，最高吞吐量（ MB/ 秒）或最高已用物理容量对集群进行排序。

查看单个集群时，您可以选择按最高 IOPS ，最高吞吐量（ MB/ 秒）或最高已用逻辑容量排序的工作负载。

* 相关信息 *

link:../events/task_fix_issues_using_um_automatic_remediations.html["使用 Unified Manager 自动修复解决问题"]

link:../performance-checker/task_display_information_about_performance_event.html["显示有关性能事件的信息"]

link:../performance-checker/concept_manage_performance_using_perf_capacity_available_iops.html["使用性能容量和可用 IOPS 信息管理性能"]

link:../health-checker/reference_health_volume_details_page.html["卷 / 运行状况详细信息页面"]

link:../performance-checker/reference_performance_event_analysis_and_notification.html["性能事件分析和通知"]

link:../events/reference_description_of_event_severity_types.html["事件严重性类型的问题描述"]

link:../performance-checker/concept_sources_of_performance_events.html["性能事件的来源"]

link:../health-checker/concept_manage_cluster_security_objectives.html["管理集群安全目标"]

link:../performance-checker/concept_monitor_cluster_performance_from_cluster_landing_page.html["从性能集群登录页面监控集群性能"]

link:../performance-checker/concept_monitor_performance_using_object_performance.html["使用性能清单页面监控性能"]
