---
permalink: storage-mgmt/task_add_space_to_data_directory_of_um_linux_host.html 
sidebar: sidebar 
keywords: add, space, data directory, linux host 
summary: '如果在最初设置 Linux 主机并安装 Unified Manager 时为 ` /opt/netapp/data` 目录分配的磁盘空间不足，无法支持 Unified Manager ，则可以在安装后通过增加 ` /opt/netapp/data` 目录上的磁盘空间来添加磁盘空间。' 
---
= 向 Linux 主机的数据目录添加空间
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果在最初设置 Linux 主机并安装 Unified Manager 时为 ` /opt/netapp/data` 目录分配的磁盘空间不足，无法支持 Unified Manager ，则可以在安装后通过增加 ` /opt/netapp/data` 目录上的磁盘空间来添加磁盘空间。

.开始之前
您必须对安装了Unified Manager的Red Hat Enterprise Linux计算机具有root用户访问权限。

建议您在增加数据目录大小之前备份 Unified Manager 数据库。

.步骤
. 以 root 用户身份登录到要添加磁盘空间的 Linux 计算机。
. 按所示顺序停止 Unified Manager 服务和关联的 MySQL 软件： `systemctl stop ocieau ocie mysqld`
. 创建一个具有足够磁盘空间的临时备份文件夹（例如， ` /backup-data` ），以将数据包含在当前 ` /opt/netapp/data` 目录中。
. 将现有 ` /opt/netapp/data` 目录的内容和权限配置复制到备份数据目录：
+
`cp -arp /opt/netapp/data/* /backup-data`

. 如果启用了 SE Linux ：
+
.. 为现有 ` /opt/netapp/data` 文件夹上的文件夹获取 SE Linux 类型：
+
`se_type=`ls -Z /opt/netapp/data| awk '{print $4}'| awk -F: '{print $3}'| head -1`

+
系统将返回类似于以下内容的确认消息：

+
[listing]
----
echo $se_type
mysqld_db_t
----
.. 运行 `chcon` 命令为备份目录设置 SE Linux 类型：
+
`chcon -R -type=mysqld_db_t /backup-data`



. 删除 ` /opt/netapp/data` 目录的内容：
+
.. `cd /opt/netapp/data`
.. `rm -rf *`


. 通过 LVM 命令或添加额外磁盘，将 ` /opt/netapp/data` 目录的大小扩展到至少 150 GB 。
+
[NOTE]
====
如果您已从磁盘创建了 ` /opt/netapp/data` ，则不应尝试将 ` /opt/netapp/data` 作为 NFS 或 CIFS 共享挂载。因为在这种情况下，如果您尝试扩展磁盘空间，某些 LVM 命令（例如 `resize` 和 `extend` ）可能无法按预期工作。

====
. 确认 ` /opt/netapp/data` 目录所有者（ mysql ）和组（ root ）保持不变：
+
`ls -ltr /opt/netapp/` grep data

+
系统将返回类似于以下内容的确认消息：

+
[listing]
----
drwxr-xr-x.  17 mysql root  4096 Aug 28 13:08 data
----
. 如果启用了 SE Linux ，请确认 ` /opt/netapp/data` 目录的上下文仍设置为 mysqld_db_t ：
+
.. `轻触 /opt/netapp/data/abc`
.. `ls -Z /opt/netapp/data/abc`
+
系统将返回类似于以下内容的确认消息：

+
[listing]
----
-rw-r--r--. root root unconfined_u:object_r:mysqld_db_t:s0 /opt/netapp/data/abc
----


. 删除文件 `abc` ，以便此无关文件将来不发生原因会出现数据库错误。
. 将 `backup-data` 中的内容复制回扩展后的 ` /opt/netapp/data` 目录：
+
`cp -arp /backup-data/* /opt/netapp/data/`

. 如果启用了 SE Linux ，请运行以下命令：
+
`chcon -R -type=mysqld_db_t /opt/netapp/data`

. 启动 MySQL 服务：
+
`systemctl start mysqld`

. 启动 MySQL 服务后，按所示顺序启动 ocie 和 ocieau 服务：
+
`systemctl start ocie ocieau`

. 启动所有服务后，删除备份文件夹 ` /backup-data` ：
+
`rm -rf /backup-data`


