---
permalink: storage-mgmt/task_provision_fileshares.html 
sidebar: sidebar 
keywords: provision, file, share, volumes 
summary: 您可以从配置工作负载页面在现有集群和 Storage Virtual Machine （ Storage VM ）上创建支持 CIFS/SMB 和 NFS 协议的文件共享卷。 
---
= 配置文件共享卷
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以从配置工作负载页面在现有集群和 Storage Virtual Machine （ Storage VM ）上创建支持 CIFS/SMB 和 NFS 协议的文件共享卷。

* 您需要的内容 *

* Storage VM 必须具有用于配置文件共享卷的空间。
* 应在 Storage VM 上启用 SMB 和 NFS 服务之一或两者。
* 要选择并分配工作负载的性能服务级别（ PSL ）和存储效率策略（ SEP ），必须在开始创建工作负载之前创建这些策略。


.步骤
. 在 * 配置工作负载 * 页面上，添加要创建的工作负载的名称，然后从可用列表中选择集群。
. 根据选定的集群， * 存储 VM* 字段将筛选该集群的可用 Storage VM 。从列表中选择所需的 Storage VM 。
+
根据 Storage VM 上支持的 SMB 和 NFS 服务，将在主机信息部分中启用 NAS 选项。

. 在存储和优化部分中，为工作负载分配存储容量和 PSL 以及 SEP （可选）。
+
SEP 的规范将分配给 LUN ， PSL 的定义将在创建工作负载时应用于工作负载。

. 如果要强制实施已分配给工作负载的 PSL ，请选中 * 强制实施性能限制 * 复选框。
+
为工作负载分配 PSL 可确保创建工作负载的聚合能够支持在相应策略中定义的性能和容量目标。例如，如果为工作负载分配了 "Extreme Performance" PSL ，则要配置工作负载的聚合应能够支持 "Extreme Performance" 策略的性能和容量目标，例如 SSD 存储。

+
[NOTE]
====
除非选中此复选框，否则 PSL 不会应用于此工作负载，并且此工作负载在信息板上的状态将显示为未分配。

====
. 选择 * NAS * 选项。
+
如果您看不到已启用 * nas* 选项，请验证您选择的 Storage VM 是否支持 SMB 或 NFS ，或者同时支持这两者。

+
[NOTE]
====
如果您的 Storage VM 同时启用了 SMB 和 NFS 服务，则可以选中 * 通过 NFS* 共享和 * 通过 SMB* 共享复选框，并创建一个同时支持 NFS 和 SMB 协议的文件共享。如果要创建 SMB 或 CIFS 共享，请仅选中相应的复选框。

====
. 对于 NFS 文件共享卷，指定用于访问文件共享卷的主机或网络的 IP 地址。您可以为多个主机输入逗号分隔值。
+
添加主机 IP 地址时，将运行内部检查，以便将主机详细信息与 Storage VM 进行匹配，并为此主机创建导出策略，如果存在现有策略，则会重复使用此策略。如果为同一主机创建了多个 NFS 共享，则会对所有文件共享重复使用具有匹配规则的同一主机的可用导出策略。在使用 API 配置 NFS 共享时，可以通过提供特定策略密钥来指定单个策略的规则或重复使用策略。

. 对于 SMB 共享，指定可以访问 SMB 共享的用户或用户组并分配所需权限。对于每个用户组，在创建文件共享期间会生成一个新的访问控制列表（ ACL ）。
. 单击 * 保存 * 。
+
此工作负载将添加到存储工作负载列表中。


