---
permalink: storage-mgmt/task_change_time_um_retains_event_performance_data.html 
sidebar: sidebar 
keywords: change, length, time, unified manager, retains, event, performance, data 
summary: 默认情况下， Unified Manager 会将所有受监控集群的事件数据和性能数据存储 6 个月。之后，系统将自动删除旧数据，以便为新数据腾出空间。此默认时间范围适用于大多数配置，但包含许多集群和节点的大型配置可能需要缩短保留期限，以便 Unified Manager 以最佳状态运行。 
---
= 更改 Unified Manager 保留事件和性能数据的时间长度
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
默认情况下， Unified Manager 会将所有受监控集群的事件数据和性能数据存储 6 个月。之后，系统将自动删除旧数据，以便为新数据腾出空间。此默认时间范围适用于大多数配置，但包含许多集群和节点的大型配置可能需要缩短保留期限，以便 Unified Manager 以最佳状态运行。

* 您需要的内容 *

您必须具有应用程序管理员角色。

您可以在 " 数据保留 " 页面中更改这两种类型数据的保留期限。这些设置会影响此 Unified Manager 实例正在监控的所有集群中的数据保留。

[NOTE]
====
Unified Manager 每 5 分钟收集一次性能统计信息。每天将 5 分钟的统计信息汇总为每小时性能统计信息。默认情况下，它会保留 30 天的 5 分钟历史性能数据和 6 个月的每小时汇总性能数据。

====
只有当空间即将用尽或者备份和其他操作需要很长时间才能完成时，才应缩短保留期限。缩短保留期限会产生以下影响：

* 旧性能数据将在午夜后从 Unified Manager 数据库中删除。
* 旧事件数据将立即从 Unified Manager 数据库中删除。
* 保留期限之前的事件将无法再在用户界面中查看。
* 用户界面中显示每小时性能统计信息的位置在保留期限之前将为空。
* 如果事件保留期限超过性能数据保留期限，则性能滑块下将显示一条消息，警告您较早的性能事件可能在其关联图表中没有后备数据。


.步骤
. 在左侧导航窗格中，单击 * 策略 * > * 数据保留 * 。
. 在 * 数据保留 * 页面中，选择事件保留或性能数据保留区域中的滑块工具，并将其移动到数据应保留的月数，然后单击 * 保存 * 。

