---
permalink: storage-mgmt/task_add_clusters.html 
sidebar: sidebar 
keywords: add cluster 
summary: 您可以将集群添加到 Active IQ Unified Manager 中，以便监控集群。这包括能够获取集群的运行状况，容量，性能和配置等集群信息，以便您可以发现并解决可能发生的任何问题。 
---
= 添加集群
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以将集群添加到 Active IQ Unified Manager 中，以便监控集群。这包括能够获取集群的运行状况，容量，性能和配置等集群信息，以便您可以发现并解决可能发生的任何问题。

* 您需要的内容 *

* 您必须具有应用程序管理员角色或存储管理员角色。
* 您必须具有集群的主机名或集群管理 IP 地址（ IPv4 或 IPv6 ）。
+
使用主机名时，必须解析为集群管理 LIF 的集群管理 IP 地址。如果使用节点管理 LIF ，则操作将失败。

* 要访问集群，您必须具有用户名和密码。
+
此帐户必须具有_admin_角色、并且应用程序访问权限设置为_ontapi_、_console _和_http_。

* 您必须知道要使用 HTTPS 协议连接到集群的端口号（通常为端口 443 ）。
* 集群必须运行 ONTAP 9.1 或更高版本的软件。
* Unified Manager 服务器上必须有足够的空间。如果已占用的空间超过 90% ，则系统将阻止您向服务器添加集群。
* 您拥有所需的证书。需要两种类型的证书：
+
* 服务器证书 * ：用于注册。要添加集群，需要有效的证书。如果服务器证书到期，您应重新生成该证书并重新启动 Unified Manager ，以便重新自动注册服务。有关生成证书的信息，请参见知识库（ KB ）文章： https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_renew_an_SSL_certificate_in_ONTAP_9["如何在 ONTAP 9 中续订 SSL 证书"]

+
* 客户端证书 * ：用于身份验证。要添加集群，需要有效的证书。您不能将证书已过期的集群添加到 Unified Manager 中，如果客户端证书已过期，则应在添加集群之前重新生成该集群。但是，如果已添加且 Unified Manager 正在使用的集群的此证书到期，则 EMS 消息传送功能将在证书过期后继续运行。您不需要重新生成客户端证书。



[NOTE]
====
您可以使用 Unified Manager NAT IP 地址添加位于 NAT/ 防火墙后面的集群。任何已连接的 Workflow Automation 或 SnapProtect 系统也必须位于 NAT/ 防火墙后面， SnapProtect API 调用必须使用 NAT IP 地址来标识集群。

====
* 必须单独添加 MetroCluster 配置中的每个集群。
* 一个 Unified Manager 实例可以支持特定数量的节点。如果您需要监控的环境超出支持的节点数，则必须安装一个额外的 Unified Manager 实例以监控某些集群。
* 您可以通过两个 Unified Manager 实例监控一个集群，但前提是您已在集群上配置了另一个集群管理 LIF ，以便 Unified Manager 的每个实例都通过不同的 LIF 进行连接。


.步骤
. 在左侧导航窗格中，单击 * 存储管理 * > * 集群设置 * 。
. 在 Cluster Setup 页面上，单击 * 添加 * 。
. 在添加集群对话框中，根据需要指定值，然后单击 * 提交 * 。
. 在授权主机对话框中，单击 * 查看证书 * 以查看有关集群的证书信息。
. 单击 * 是 * 。
+
只有在首次添加集群时， Unified Manager 才会检查证书。Unified Manager 不会检查对 ONTAP 的每次 API 调用的证书。



发现新集群的所有对象后， Unified Manager 将开始收集过去 15 天的历史性能数据。这些统计信息是使用数据连续性收集功能收集的。添加集群后，此功能会立即为您提供超过两周的集群性能信息。数据连续性收集周期完成后，系统会默认每五分钟收集一次实时集群性能数据。

[NOTE]
====
由于收集 15 天的性能数据需要占用大量 CPU 资源，因此建议您错开添加新集群的时间，以便不会在太多集群上同时运行数据连续性收集轮询。此外，如果您在数据连续性收集期间重新启动 Unified Manager ，则收集将暂停，并且性能图表中会显示缺少的时间范围。

====
[TIP]
====
如果您收到一条错误消息，指出无法添加集群，请检查是否存在以下问题：

* 如果两个系统上的时钟未同步，并且 Unified Manager HTTPS 证书开始日期晚于集群上的日期。您必须确保时钟使用 NTP 或类似服务进行同步。
* 如果集群已达到 EMS 通知目标的最大数量，则无法添加 Unified Manager 地址。默认情况下，只能在集群上定义 20 个 EMS 通知目标。


====
* 相关信息 *

link:../config/task_add_users.html["添加用户"]

link:../health-checker/task_view_cluster_list_and_details.html["查看集群列表和详细信息"]
