---
permalink: health-checker/reference_setup_autosupport_page.html 
sidebar: sidebar 
keywords: autosupport, messages, support bundles, technical support 
summary: 通过 AutoSupport 页面，您可以向技术支持团队发送预定义的按需 AutoSupport 消息，以确保环境正常运行，并帮助您维护环境的完整性。默认情况下， AutoSupport 处于启用状态，不应将其禁用，这样您才能获得 NetAppActive IQ 的优势。 
---
= 将 AutoSupport 消息和支持包发送给技术支持
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过 AutoSupport 页面，您可以向技术支持团队发送预定义的按需 AutoSupport 消息，以确保环境正常运行，并帮助您维护环境的完整性。默认情况下， AutoSupport 处于启用状态，不应将其禁用，这样您才能获得 NetAppActive IQ 的优势。

您可以根据需要在消息中发送有关 Unified Manager 服务器的诊断系统信息和详细数据，计划定期发送消息，甚至生成支持包并将其发送给技术支持团队。

[NOTE]
====
具有存储管理员角色的用户可以生成按需 AutoSupport 消息和支持包并将其发送给技术支持。但是，只有管理员或维护用户才能启用或禁用定期 AutoSupport 以及配置 HTTP 设置，如设置 HTTP 代理服务器一节所述。在需要使用 HTTP 代理服务器的环境中，存储管理员应先完成配置，然后才能将按需 AutoSupport 消息和支持包发送给技术支持。

====


== 发送按需 AutoSupport 消息

您可以生成按需消息并将其发送给技术支持，指定的电子邮件收件人或两者。

.步骤
. 导航到 * 常规 * > * AutoSupport * ，然后执行以下一项或两项操作：
. 如果要将 AutoSupport 消息发送给技术支持，请选中 * 发送给技术支持 * 复选框。
. 如果要将 AutoSupport 消息发送到特定电子邮件收件人，请选中 * 发送到电子邮件收件人 * 复选框，然后输入收件人的电子邮件地址。
. 单击 * 保存 * 。
. 单击 * 生成并发送 AutoSupport * 。




== 启用定期 AutoSupport

您可以定期向技术支持发送特定的预定义消息，以进行问题描述诊断和解决。默认情况下，此功能处于启用状态。如果禁用，则管理员或维护用户可以启用这些设置。

.步骤
. 导航到 * 常规 * > * AutoSupport * 。
. 在定期 AutoSupport 部分中，选中 * 启用定期向 Active IQ 发送 AutoSupport 数据 * 复选框。
. 如果需要，请按照设置 HTTP 代理服务器一节中的说明定义 HTTP 代理服务器的名称，端口和身份验证信息。
. 单击 * 保存 * 。




== 上传按需支持包

您可以根据故障排除要求生成支持包并将其发送给技术支持。Unified Manager 仅存储最近生成的两个支持包。旧的支持包将从系统中删除。

由于某些类型的支持数据可能会占用大量集群资源或需要很长时间才能完成，因此，在选择完整的支持包时，您可以包括或排除特定的数据类型以减小支持包大小。您还可以选择创建一个轻型支持包，该包只包含 30 天的日志和配置数据库记录，它不包括性能数据，采集录制文件和服务器堆转储。

.步骤
. 导航到 * 常规 * > * AutoSupport * 。
. 在按需支持包部分中，单击 * 生成并发送支持包 * 。
. 要向技术支持发送轻型支持包，请在生成和发送支持包弹出窗口中选中 "* 生成轻型支持包 "* 复选框。
. 或者，要发送完整的支持包，请选中 * 生成完整的支持包 * 复选框。选择要在支持包中包含或排除的特定数据类型。
+
[NOTE]
====
即使不选择任何数据类型，仍会使用其他 Unified Manager 数据生成支持包。

====
. 选中 * 将捆绑包发送给技术支持 * 复选框以生成捆绑包并将其发送给技术支持。如果不选中此复选框，则会在 Unified Manager 服务器本地生成并存储此捆绑包。生成的支持包可在以下位置供日后使用： VMware 系统上的 /support 目录， Linux 系统上的 ` /opt/netapp/data/support/` 以及 Windows 系统上的 `ProgramData\NetApp\OnCommandAppData\ocum\support` 。
. 单击 * 发送 * 。




== 设置 HTTP 代理服务器

如果您的环境不提供从Unified Manager服务器直接访问的权限、您可以指定一个代理来提供Internet访问、以便向支持部门发送AutoSupport 内容。此部分仅适用于管理员和维护用户。

* * 使用 HTTP 代理 *
+
选中此框可标识用作 HTTP 代理的服务器。

+
输入代理服务器的主机名或 IP 地址，以及用于连接到该服务器的端口号。

* * 使用身份验证 *
+
如果需要提供身份验证信息来访问用作 HTTP 代理的服务器，请选中此框。

+
输入向 HTTP 代理进行身份验证所需的用户名和密码。



[NOTE]
====
不支持仅提供基本身份验证的 HTTP 代理。

====