---
permalink: health-checker/task_restore_snapshot_backup.html 
sidebar: sidebar 
keywords: restore, linux, snapshot, backup, windows 
summary: 如果发生数据丢失或数据损坏，您可以将 Unified Manager 还原到先前的稳定状态，同时最大程度地减少数据丢失。您可以使用 Unified Manager 维护控制台将 Unified Manager Snapshot 数据库还原到本地或远程操作系统。 
---
= 还原 Linux 和 Windows 的 Snapshot 备份
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果发生数据丢失或数据损坏，您可以将 Unified Manager 还原到先前的稳定状态，同时最大程度地减少数据丢失。您可以使用 Unified Manager 维护控制台将 Unified Manager Snapshot 数据库还原到本地或远程操作系统。

* 您需要的内容 *

* 您必须具有 Linux 主机的 root 用户凭据以及安装了 Unified Manager 的 Windows 主机的管理权限。
* 您必须拥有有权登录到 Unified Manager 服务器维护控制台的用户 ID 和密码。


还原功能是针对平台和版本的。您只能在同一版本的 Unified Manager 上还原 Unified Manager 备份。

.步骤
. 连接到 Unified Manager 系统的 IP 地址或完全限定域名。
+
|===


 a| 
* Linux *



 a| 
安全外壳



 a| 
* Windows *



 a| 
Power Shell

|===
. 使用 root 用户凭据登录到系统。
. 输入命令 `mainstion_console` 并按 Enter 键。
. 在维护控制台 * 主菜单 * 中，输入 * 备份还原 * 选项的编号。
. 输入 * 使用 NetApp Snapshot* 进行备份和还原的编号。
+
如果要还原到新服务器，则在安装 Unified Manager 后，请勿启动用户界面，也不要在安装完成后配置任何集群，用户或身份验证设置。输入 * 配置 NetApp Snapshot 备份 * 的编号，然后按照原始系统上配置的方式配置 Snapshot 备份设置。

. 输入 * 使用 NetApp Snapshot* 还原的数字。
. 选择要还原的 Snapshot 备份文件，然后按 * 输入 * 。
. 还原过程完成后，登录到 Unified Manager 用户界面。


还原备份后，如果 Workflow Automation 服务器不起作用，请执行以下步骤：

. 在 Workflow Automation 服务器上，更改 Unified Manager 服务器的 IP 地址以指向最新的计算机。
. 在 Unified Manager 服务器上，如果在步骤 1 中采集失败，请重置数据库密码。

