---
permalink: health-checker/task_restore_snapshot_backup.html 
sidebar: sidebar 
keywords: restore, unified manager, snapshot copy, copies, 
summary: 如果发生数据丢失或数据损坏，您可以将 Unified Manager 还原到先前的稳定状态，同时最大程度地减少数据丢失。您可以使用 Unified Manager 维护控制台将 Unified Manager Snapshot 数据库还原到本地或远程操作系统。 
---
= 使用Snapshot副本还原Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果发生数据丢失或数据损坏，您可以将 Unified Manager 还原到先前的稳定状态，同时最大程度地减少数据丢失。您可以使用 Unified Manager 维护控制台将 Unified Manager Snapshot 数据库还原到本地或远程操作系统。

* 您需要的内容 *

* 您必须具有 Linux 主机的 root 用户凭据以及安装了 Unified Manager 的 Windows 主机的管理权限。
* 您必须拥有有权登录到 Unified Manager 服务器维护控制台的用户 ID 和密码。


还原功能是针对平台和版本的。您只能在同一版本的 Unified Manager 上还原 Unified Manager 备份。

.步骤
. 连接到 Unified Manager 系统的 IP 地址或完全限定域名。
+
** Linux：安全Shell
** Windows：Power Shell


. 使用 root 用户凭据登录到系统。
. 输入命令 `mainstion_console` 并按 Enter 键。
. 在维护控制台*主菜单*中、为*备份还原*选项输入4。
. 输入2以选择"*使用NetApp Snapshot*备份和还原"。
+
如果要还原到新服务器，则在安装 Unified Manager 后，请勿启动用户界面，也不要在安装完成后配置任何集群，用户或身份验证设置。输入1以选择*配置NetApp Snapshot备份*、并像在原始系统上一样配置Snapshot副本的设置。

. 输入3以选择*使用NetApp Snapshot*还原。
. 选择要从中还原Unified Manager的Snapshot副本。按 * 输入 * 。
. 还原过程完成后，登录到 Unified Manager 用户界面。


还原备份后，如果 Workflow Automation 服务器不起作用，请执行以下步骤：

. 在 Workflow Automation 服务器上，更改 Unified Manager 服务器的 IP 地址以指向最新的计算机。
. 在 Unified Manager 服务器上，如果在步骤 1 中采集失败，请重置数据库密码。

