---
permalink: health-checker/task_restore_mysql_db_on_linux_or_centos.html 
sidebar: sidebar 
keywords: restore, linux system, mysql, database, backup 
summary: 如果发生数据丢失或数据损坏，您可以将 Unified Manager 还原到先前的稳定状态，同时最大程度地减少数据丢失。您可以使用 Unified Manager 维护控制台将 Unified Manager 数据库还原到本地或远程 Red Hat Enterprise Linux 或 CentOS 系统。 
---
= 在 Linux 系统上还原 MySQL 数据库备份
:icons: font
:imagesdir: ../media/


[role="lead"]
如果发生数据丢失或数据损坏，您可以将 Unified Manager 还原到先前的稳定状态，同时最大程度地减少数据丢失。您可以使用 Unified Manager 维护控制台将 Unified Manager 数据库还原到本地或远程 Red Hat Enterprise Linux 或 CentOS 系统。

* 您需要的内容 *

* 您必须具有安装 Unified Manager 的 Linux 主机的 root 用户凭据。
* 您必须拥有有权登录到 Unified Manager 服务器维护控制台的用户 ID 和密码。
* 您必须已将 Unified Manager 备份文件和数据库存储库目录的内容复制到要执行还原操作的系统。
+
建议您将备份文件复制到默认目录 `data/ocum` backup.必须将数据库存储库文件复制到 /`ocum-backup` 目录下的 /m `datdatabase-dump -repod` 子目录中。

* 备份文件的类型必须为 ` .7z` 。


还原功能是针对平台和版本的。您只能在同一版本的 Unified Manager 上还原 Unified Manager 备份。您可以将 Linux 备份文件或虚拟设备备份文件还原到 Red Hat Enterprise Linux 或 CentOS 系统。

[TIP]
====
如果备份文件夹名称包含空格，则必须使用双引号将绝对路径或相对路径包括在内。

====
.步骤
. 如果要还原到新服务器，则在安装 Unified Manager 后，请勿启动用户界面，也不要在安装完成后配置任何集群，用户或身份验证设置。备份文件会在还原过程中填充此信息。
. 使用安全 Shell 连接到 Unified Manager 系统的 IP 地址或完全限定域名。
. 使用维护用户（ umadmin ）名称和密码登录到系统。
. 输入命令 `mainstion_console` 并按 Enter 键。
. 在维护控制台 * 主菜单 * 中，输入 * 备份还原 * 选项的编号。
. 输入 * 还原 MySQL Backup* 的编号。
. 出现提示时，输入备份文件的绝对路径。
+
[listing]
----
Bundle to restore from: /data/ocum-backup/UM_9.8.N151113.1348_backup_rhel_02-20-2020-04-45.7z
----
+
还原操作完成后，您可以登录到 Unified Manager 。



还原备份后，如果 OnCommand Workflow Automation 服务器不起作用，请执行以下步骤：

. 在 Workflow Automation 服务器上，更改 Unified Manager 服务器的 IP 地址以指向最新的计算机。
. 在 Unified Manager 服务器上，如果在步骤 1 中采集失败，请重置数据库密码。

