---
permalink: install-vapp/qsg-vapp.html 
sidebar: sidebar 
keywords: quick start guide, getting started, QSG, VMWare QSG, vApp QSG, quick installation 
summary: 基于 VMware vSphere 平台的 Unified Manager 快速入门指南。 
---
= VMware安装快速入门说明
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以下载 `.tar` 包含根证书的文件 `README` 文件和 `OVA` 归档、并将Unified Manager部署为虚拟设备。



== 系统要求

* 操作系统：VMware ESXi 8.0
* RAM ： 12 GB
* CPU ：总计 9572 MHz
* 可用磁盘空间： 5 GB （精简配置）， 152 GB （厚配置）


有关详细的系统要求，请参见 link:../install-vapp/concept_requirements_for_installing_unified_manager.html["Unified Manager 的安装要求"] 和 link:http://mysupport.netapp.com/matrix["互操作性表"]。



== 安装 Active IQ Unified Manager



=== 下载安装程序：

. 下载 `.tar` 包含根证书的文件 `README` 文件和 `OVA` 文件
. 将文件保存到 vSphere Client 可访问的本地目录或网络目录中。
. 在下载的目录中 `.tar` 文件中、输入 `tar -xvzf ActiveIQUnifiedManager-<version>.tar.gz` 命令：+所需的 `OVA` 文件、根证书和 `README` 文件将解压缩到目标目录。




=== 验证完整性

您可以验证的完整性 `OVA` 按照中提供的步骤执行文件 `README` 文件



=== 安装 Unified Manager

. 在 vSphere Client 中，单击 * 文件 > 部署 OVF 模板 * 。
. 找到 OVA 文件并使用向导在 ESXi 服务器上部署虚拟设备。
. 在查看详细信息页面的发布者部分中、显示消息  `Entrust Code Signing - OVCS2 (Trusted certificate)` 确认已下载的的的完整性 `OVA` 文件消息 `Entrust Code Signing - OVCS2 (Invalid certificate)`、将VMware vCenter Server升级到7.0U3C或更高版本。
. 在自定义模板页面的属性选项卡中、根据需要填充要执行的安装类型的字段：
+
** 对于静态配置，请在所有字段中输入所需信息。不需要为 * 二级 DNS* 字段添加信息。
** 对于使用 IPv4 的 DHCP ，请勿在任何字段中添加任何信息。
** 对于使用 IPv6 的 DHCP ，请选中 " 启用自动 IPv6 寻址 " 复选框。请勿在任何其他字段中添加任何信息。


. 启动虚拟机。
. 单击控制台选项卡以查看初始启动过程。
. 配置时区。
. 输入 Unified Manager 维护用户名和密码。


安装结束时，将显示连接到 Unified Manager Web UI 的信息。
