---
permalink: install-vapp/task_deploy_unified_manager_vapp.html 
sidebar: sidebar 
keywords: deploy, unified manager 
summary: 部署 Unified Manager 包括下载软件，部署虚拟设备，创建维护用户名和密码以及在 Web UI 中执行初始设置。 
---
= 部署 Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
部署 Unified Manager 包括下载软件，部署虚拟设备，创建维护用户名和密码以及在 Web UI 中执行初始设置。

.开始之前
* 您应验证并完成部署的系统要求。
+
请参见 link:concept_requirements_for_installing_unified_manager.html["系统要求"]。

* 确保您具有以下信息：
+
** NetApp 支持站点的登录凭据
** 用于访问 VMware vCenter Server 和 vSphere Web Client 的凭据
** 要部署 Unified Manager 虚拟设备的 ESXi 服务器的 IP 地址
** 有关数据中心的详细信息，例如数据存储库中的存储空间和内存要求
** 如果要使用 IPv6 寻址，应在主机上启用 IPv6 。




您可以将 Unified Manager 部署为 VMware ESXi 服务器上的虚拟设备。

您应使用 VMware 控制台访问维护控制台，而不是使用 SSH 。

[NOTE]
====
从 Unified Manager 9.8 开始， VMware Tools 已替换为 Open VM Tools （`open-vm-tools` ）。您不再需要在安装过程中安装 VMware Tools ，因为 Unified Manager 安装包中包含 `open-vm-tools` 。

====
完成部署和初始设置后，您可以在维护控制台中添加集群或配置其他网络设置，然后访问 Web UI 。

.步骤
. 按照中的步骤进行操作 link:task_download_unified_manager_ova_file.html["下载 Unified Manager"]。
. 此外、请按照中的步骤进行操作 link:task_deploy_unified_manager_virtual_appliance_vapp.html["部署 Unified Manager 虚拟设备"]。

