---
permalink: install-windows/task_change_jboss_password_on_windows.html 
sidebar: sidebar 
keywords: change, jboss, password 
summary: 您可以重置在安装期间设置的实例专用 JBoss 密码。如果您的站点需要此安全功能来覆盖 Unified Manager 安装设置，您可以选择重置密码。此操作还会更改 JBoss 用于访问 MySQL 的密码。 
---
= 更改 JBoss 密码
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以重置在安装期间设置的实例专用 JBoss 密码。如果您的站点需要此安全功能来覆盖 Unified Manager 安装设置，您可以选择重置密码。此操作还会更改 JBoss 用于访问 MySQL 的密码。

.开始之前
* 对于安装了 Unified Manager 的系统，您应具有 Windows 管理员权限。
* 您应具有 MySQL root 用户的密码。
* 您应该能够访问目录中由 NetApp 提供的 `password.bat` 脚本
+
`C：\Program Files\NetApp\Findes\bin`。



.步骤
. 以管理员用户身份登录到 Unified Manager 主机。
. 使用 Windows 服务控制台停止以下 Unified Manager 服务：
+
** NetApp Active IQ 采集服务（ Ocie-au ）
** NetApp Active IQ 管理服务器服务（ Oncommandsvc ）


. 启动 `password.bat` 脚本以开始密码更改过程：
+
`C ： \Program Files\NetApp\Findes\bin> password.bat resetJBossPassword`

. 出现提示时，输入 MySQL root 用户密码。
. 出现提示时，输入新的 JBoss 用户密码，然后再次输入以进行确认。
+
请注意，密码应介于 8 到 16 个字符之间，并且必须至少包含一个数字，一个大写和一个小写字符，以及至少一个特殊字符：

+
` + ！@ %^ * - _+=[] ： <>. ？ /~ +`

. 脚本完成后，使用 Windows 服务控制台启动 Unified Manager 服务：
+
** NetApp Active IQ 管理服务器服务（ Oncommandsvc ）
** NetApp Active IQ 采集服务（ Ocie-au ）


. 启动所有服务后，您可以登录到 Unified Manager UI 。

