---
permalink: install-windows/task_upgrade_to_unified_manager_on_microsoft_windows.html 
sidebar: sidebar 
keywords: upgrade, unified manager 
summary: 您可以通过在 Windows 平台上下载并运行安装文件来升级 Unified Manager 。 
---
= 升级 Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以通过在Windows平台上下载并运行安装文件将Unified Manager 9.13或9.14升级到9.16。

.开始之前
* 要升级 Unified Manager 的系统应满足系统和软件要求。
+
请参见 link:concept_virtual_infrastructure_or_hardware_system_requirements.html["硬件系统要求"]。

+
请参见 link:reference_windows_software_and_installation_requirements.html["Windows 软件和安装要求"]。

+
[NOTE]
====
从 Unified Manager 9.5 开始， OpenJDK 会随安装包提供并自动安装。从 Unified Manager 9.5 开始，不支持 Oracle Java 。

====
+
[NOTE]
====
在开始升级之前，请确保系统上已安装 Microsoft .NET 4.5.2 或更高版本。

====
* 在 Unified Manager 升级期间， MySQL Community Edition 会自动升级。如果系统上安装的MySQL版本早于8.4.4、则Unified Manager升级过程会自动将MySQL升级到8.4.4。您不能将早期版本的MySQL独立升级到8.4.4。
* 除ASA R2系统之外、所有集群均受支持。
* 您应具有 Windows 管理员权限。确保您的用户名不以感叹号 "` ！` " 开头。如果运行此安装的用户名以 "` ！` " 开头，则安装 Unified Manager 可能会失败。
* 您应具有有效的凭据才能登录到 NetApp 支持站点。
* 为避免数据丢失，如果在升级期间存在问题描述，则应已为 Unified Manager 计算机创建备份。
* 您应具有足够的可用磁盘空间来执行升级。
+
安装驱动器上的可用空间应大于数据目录大小 2.5 GB 。升级将停止并显示一条错误消息，指示在可用空间不足时要添加的空间量。

* 在升级期间，系统可能会提示您确认是要保留先前的默认设置以将性能数据保留 13 个月，还是将其更改为 6 个月。确认后，将清除 6 个月后的历史性能数据。
* 在升级之前，您应关闭 _<INSTALLDIR>\JDK_ 和 _MySQL Data Directory_ 中所有打开的文件或文件夹。
* 如果Windows系统上安装了活动防病毒软件、则Unified Manager升级可能会失败。在升级Unified Manager之前、应禁用系统上的所有病毒扫描软件。


在升级过程中， Unified Manager 不可用。在升级 Unified Manager 之前，您应完成所有正在运行的操作。

如果 Unified Manager 与 OnCommand Workflow Automation 实例配对，并且这两种产品都有新版本的软件，则必须断开这两种产品的连接，然后在执行升级后设置新的 Workflow Automation 连接。如果您仅对其中一个产品执行升级，则应在升级后登录到 Workflow Automation ，并验证它是否仍在从 Unified Manager 获取数据。

.步骤
. 登录到 NetApp 支持站点，然后导航到 Unified Manager 的 Download 页面：
+
https://mysupport.netapp.com/site/products/all/details/activeiq-unified-manager/downloads-tab["NetApp 支持站点"^]。

. 选择所需的 Unified Manager 版本并接受最终用户许可协议（ EULA ）。
. 将Unified Manager Windows安装文件或zip文件下载到Windows系统上的目标目录。如果需要、解压缩此zip文件、然后导航到安装文件所在的目录。右键单击并以管理员身份运行 Unified Manager 安装程序可执行文件（ .exe ）。
+
Unified Manager 将提示您显示以下消息：

+
[listing]
----
This setup will perform an upgrade of Unified Manager. Do you want to continue?
----
. 单击 * 是 * ，然后单击 * 下一步 * 。
. 输入在安装期间设置的 MySQL84 根密码，然后单击 * 下一步 * 。
. 在支持的Web浏览器上的新窗口中启动Web UI、然后登录以使用升级后的Unified Manager版本。
. 如果您的Windows系统上安装了活动防病毒软件、请确保在升级完成后手动从防病毒扫描中排除以下路径：
+
** Unified Manager 数据目录
** Unified Manager 安装目录
** MySQL 数据目录




[NOTE]
====
要对 Unified Manager 执行静默升级，请运行以下命令： `ActiveIQUnifiedManager- <version\>.exe /s /v"mysql_password=<password>/qn /l* v <system_drive> ： \install.log`

====