---
permalink: install-windows/task_install_unified_manager_on_windows.html 
sidebar: sidebar 
keywords: install, unified manager 
summary: 您可以安装 Unified Manager 来监控数据存储容量，可用性，性能和保护问题并对其进行故障排除。 
---
= 安装 Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以安装 Unified Manager 来监控数据存储容量，可用性，性能和保护问题并对其进行故障排除。

* 您需要的内容 *

* 您计划安装 Unified Manager 的系统应满足系统和软件要求。
+
请参见 link:concept_virtual_infrastructure_or_hardware_system_requirements.html["硬件系统要求"]。

+
请参见 link:reference_windows_software_and_installation_requirements.html["Windows 软件和安装要求"]。

+
[NOTE]
====
从 Unified Manager 9.5 开始， OpenJDK 会随安装包提供并自动安装。从 Unified Manager 9.5 开始，不支持 Oracle Java 。

====
* 您应具有 Windows 管理员权限。确保您的用户名不以感叹号 "` ！` " 开头。如果运行此安装的用户名以 "` ！` " 开头，则安装 Unified Manager 可能会失败。
* 除ASA R2系统之外、所有集群均受支持。
* 您应具有受支持的 Web 浏览器。
* Unified Manager 维护用户密码应介于 8 到 20 个字符之间，并应包含大写字母或小写字母，数字和特殊字符。
* 维护用户或 MySQL root 用户的密码字符串不允许包含以下特殊字符： " ' ` % ， = & < > = ^ \ / （） [ ] ；：
+
允许使用以下特殊字符： ~ ！@ # $ * - ？。+



.步骤
. 使用默认本地管理员帐户登录到 Windows 。
. 登录到 NetApp 支持站点，然后导航到 Unified Manager 的 Download 页面：
+
https://mysupport.netapp.com/site/products/all/details/activeiq-unified-manager/downloads-tab["NetApp 支持站点"^]

. 选择所需的 Unified Manager 版本并接受最终用户许可协议（ EULA ）。
. 将Unified Manager Windows安装文件或zip文件下载到Windows系统上的目标目录。
. 如果需要、解压缩此zip文件、然后导航到安装文件所在的目录。
. 右键单击并以管理员身份运行 Unified Manager 安装程序可执行文件（ .exe ）。
+
Unified Manager 会检测缺少的或预先安装的第三方软件包并列出它们。如果系统中未安装所需的第三方软件包，则 Unified Manager 会在安装过程中安装这些软件包。

. 单击 * 下一步 * 。
. 输入用户名和密码以创建维护用户。
. 在 Database Connection 向导中，输入 MySQL root 密码。
. 单击 * 更改 * 为 Unified Manager 安装目录和 MySQL 数据目录指定新位置。
+
如果不更改安装目录， Unified Manager 将安装在默认安装目录中。

. 单击 * 下一步 * 。
. 在准备安装 Shield 向导中，单击 * 安装 * 。
. 安装完成后，单击 * 完成 * 。
. 如果您的Windows系统上安装了活动防病毒软件、请在安装完成后手动从防病毒扫描中排除以下路径：
+
** Unified Manager 数据目录
** Unified Manager 安装目录
** MySQL 数据目录




此安装将创建多个目录：

* 安装目录
+
这是您在安装期间指定的 Unified Manager 的根目录。示例： `C ： \Program Files\NetApp\`

* MySQL 数据目录
+
这是存储 MySQL 数据库的目录，您在安装期间指定了该目录。示例： `C ： \ProgramData\MySqlServerData\`

* Java 目录
+
这是安装 OpenJDK 的目录。示例： `C ： \Program Files\NetApp\JDK\`

* Unified Manager 应用程序数据目录（ appDataDir ）
+
此目录用于存储应用程序生成的所有数据。其中包括日志，支持包，备份以及所有其他附加数据。示例： `C ： \ProgramData\NetApp\OnCommandAppData\`



您可以访问 Web UI 以执行 Unified Manager 的初始设置，如中所述 link:../config/concept_configure_unified_manager.html["正在配置 Active IQ Unified Manager"]。
