---
permalink: config/reference_additional_menu_options.html 
sidebar: sidebar 
keywords: additional menu, options 
summary: 您可以使用以下菜单选项在 Unified Manager 服务器上执行各种管理任务。 
---
= 其他菜单选项
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用以下菜单选项在 Unified Manager 服务器上执行各种管理任务。

可以使用以下菜单选项：

* * 重置服务器证书 *
+
重新生成 HTTPS 服务器证书。

+
您可以通过单击 * 常规 * > * HTTPS 证书 * > * 重新生成 HTTPS 证书 * 在 Unified Manager 图形用户界面中重新生成服务器证书。

* * 禁用 SAML 身份验证 *
+
禁用 SAML 身份验证，以便身份提供程序（ IdP ）不再为访问 Unified Manager 图形用户界面的用户提供登录身份验证。如果具有 IdP 服务器或 SAML 配置的问题描述阻止用户访问 Unified Manager 图形用户界面，则通常会使用此控制台选项。

* * 外部数据提供程序 *
+
提供了将 Unified Manager 连接到外部数据提供程序的选项。建立连接后，性能数据将发送到外部服务器，以便存储性能专家可以使用第三方软件绘制性能指标图表。此时将显示以下选项：

+
** * 显示服务器配置 * - 显示外部数据提供程序的当前连接和配置设置。
** * 添加 / 修改服务器连接 * —用于输入外部数据提供程序的新连接设置或更改现有设置。
** * 修改服务器配置 * —用于输入外部数据提供程序的新配置设置或更改现有设置。
** * 删除服务器连接 * —删除与外部数据提供程序的连接。
+
删除此连接后， Unified Manager 将断开与外部服务器的连接。



* *备份还原*
+
有关信息、请参见下的主题 link:../health-checker/concept_manage_backup_and_restore_operations.html["管理备份和还原操作"]。

* * 性能轮询间隔配置 *
+
提供了一个选项，用于配置 Unified Manager 从集群收集性能统计数据的频率。默认收集间隔为 5 分钟。

+
如果您发现从大型集群收集的操作未按时完成，可以将此间隔更改为 10 或 15 分钟。

* * 查看 / 更改应用程序端口 *
+
提供了一个选项，可根据安全要求更改 Unified Manager 用于 HTTP 和 HTTPS 协议的默认端口。对于 HTTP ，默认端口为 80 ，对于 HTTPS ，默认端口为 443 。

* *控制对MySQL端口3306*的访问
+
控制主机对默认MySQL端口3306的访问。出于安全原因、在Linux、Windows和VMware vSphere系统上全新安装Unified Manager期间、通过此端口的访问仅限于本地主机。使用此选项可以在本地主机和远程主机之间切换此端口的可见性、也就是说、如果仅在您的环境中为本地主机启用了此端口、则也可以使此端口对远程主机可用。或者、如果为所有主机启用了、则只能将此端口的访问限制为本地主机。如果之前在远程主机上启用了访问、则在升级情形中会保留此配置。您应在更改端口可见性后检查Windows系统上的防火墙设置、如果将防火墙设置配置为限制对MySQL端口3306的访问、则应禁用这些设置。

* * 退出 *
+
退出维护控制台菜单。


