---
permalink: config/task_generate_an_https_security_certificate_ocf.html 
sidebar: sidebar 
keywords: generate, https, security, certificate 
summary: 首次安装 Active IQ Unified Manager 时，将安装默认 HTTPS 证书。您可以生成一个新的 HTTPS 安全证书来替换现有证书。 
---
= 生成 HTTPS 安全证书
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
首次安装 Active IQ Unified Manager 时，将安装默认 HTTPS 证书。您可以生成一个新的 HTTPS 安全证书来替换现有证书。

* 您需要的内容 *

您必须具有应用程序管理员角色。

重新生成证书的原因可能有多种，例如您希望为可分辨名称（ Distinguished Name ， DN ）设置更好的值，或者您希望增加密钥大小或延长到期期限，或者当前证书已过期。

如果您无法访问 Unified Manager Web UI ，则可以使用维护控制台使用相同的值重新生成 HTTPS 证书。在重新生成证书时，您可以定义密钥大小和密钥的有效期。如果在维护控制台中使用 `Reset Server Certificate` 选项，则会创建一个新的 HTTPS 证书，有效期为 397 天。此证书的 RSA 密钥大小为 2048 位。

.步骤
. 在左侧导航窗格中，单击 * 常规 * > * HTTPS 证书 * 。
. 单击 * 重新生成 HTTPS 证书 * 。
+
此时将显示重新生成 HTTPS 证书对话框。

. 根据要生成证书的方式，选择以下选项之一：
+
[cols="2*"]
|===
| 如果您要 ... | 执行此操作 ... 


 a| 
使用当前值重新生成证书
 a| 
单击 * 使用当前证书属性重新生成 * 选项。



 a| 
使用不同的值生成证书
 a| 
单击 * 更新当前证书属性 * 选项。

如果不输入新值， " 公用名 " 和 " 备用名称 " 字段将使用现有证书中的值。应将 "`Common Name` " 设置为主机的 FQDN 。其他字段不需要值，但您可以输入电子邮件，公司，部门， 城市，省 / 自治区 / 直辖市和国家 / 地区，以便在证书中填充这些值。您也可以从可用密钥大小（密钥算法为 "`RSA` " ）和有效期中进行选择。

[NOTE]
====
** 密钥大小允许的值为 `2048` ， `3072` 和 `4096` 。
** 有效期至少为 1 天，最多为 36500 天。
+
即使允许使用 36500 天的有效期，建议您使用的有效期不超过 397 天或 13 个月。由于如果您选择的有效期超过 397 天，并计划导出此证书的 CSR 并使其由知名 CA 签名，则此 CA 返回给您的签名证书的有效期将缩短为 397 天。

** 如果要从证书的 " 备用名称 " 字段中删除本地标识信息，可以选中 " 排除本地标识信息（例如本地主机） " 复选框。选中此复选框后，备用名称字段将仅使用您在字段中输入的内容。如果留空，则生成的证书将根本没有备用名称字段。


====
|===
. 单击 * 是 * 重新生成证书。
. 重新启动 Unified Manager 服务器，以使新证书生效。
. 通过查看 HTTPS 证书来验证新证书信息。

