---
permalink: config/task_add_clusters.html 
sidebar: sidebar 
keywords: add cluster 
summary: 您可以将集群添加到 Active IQ Unified Manager 中，以便监控集群。这包括能够获取集群的运行状况，容量，性能和配置等集群信息，以便您可以发现并解决可能发生的任何问题。 
---
= 添加集群
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以将集群添加到 Active IQ Unified Manager 中，以便监控集群。这包括能够获取集群的运行状况，容量，性能和配置等集群信息，以便您可以发现并解决可能发生的任何问题。

* 您需要的内容 *

* 您必须具有应用程序管理员或存储管理员角色。
* 您必须具有以下信息：
+
** Unified Manager支持内部ONTAP 集群、ONTAP Select 、Cloud Volumes ONTAP。
** 主机名或集群管理 IP 地址
+
主机名是 Unified Manager 用于连接到集群的 FQDN 或简称。主机名必须解析为集群管理 IP 地址。

+
集群管理 IP 地址必须是管理 Storage Virtual Machine （ SVM ）的集群管理 LIF 。如果使用节点管理 LIF ，则操作将失败。

** 集群必须运行 ONTAP 9.1 或更高版本的软件。
** ONTAP 管理员用户名和密码
+
此帐户必须具有_admin_角色、并且应用程序访问权限设置为_ontapi_、_console _和_http_。

** 使用 HTTPS 协议连接到集群的端口号（通常为端口 443 ）
** 您具有所需的证书：
+
* SSL (HTTPS)证书*：此证书归Unified Manager所有。全新安装的Unified Manager将生成默认的自签名SSL (HTTPS)证书。NetApp建议您将其升级到CA签名证书、以提高安全性。如果服务器证书到期、您应重新生成该证书并重新启动Unified Manager、以便服务加入新证书。有关重新生成SSL证书的详细信息、请参见 link:../config/task_generate_an_https_security_certificate_ocf.html["生成 HTTPS 安全证书"]。

+
*EMS证书*：此证书归Unified Manager所有。它用于身份验证期间从ONTAP 收到的EMS通知。

+
*用于相互TLS通信的证书*：在Unified Manager和ONTAP 之间进行相互TLS通信期间使用。系统将根据ONTAP 版本为集群启用基于证书的身份验证。如果运行ONTAP 版本的集群低于9.5、则不会启用基于证书的身份验证。

+
如果要更新旧版本的Unified Manager、则不会自动为集群启用基于证书的身份验证。但是、您可以通过修改和保存集群详细信息来启用此功能。如果证书过期、则应重新生成证书以加入新证书。有关查看和重新生成证书的详细信息、请参见 link:../storage-mgmt/task_edit_clusters.html["编辑集群"]。

+
[NOTE]
====
*** 如果您从Web UI添加集群、则基于证书的身份验证将自动启用。如果从维护控制台添加集群、则不会启用基于证书的身份验证。
*** 如果为集群启用了基于证书的身份验证、并且您从服务器备份Unified Manager并还原到另一个Unified Manager服务器、其中主机名或IP地址发生了更改、则监控集群可能会失败。要避免失败、请编辑并保存集群详细信息。有关编辑集群详细信息的详细信息、请参见 link:../storage-mgmt/task_edit_clusters.html["编辑集群"]。


====
+
*集群证书*：此证书归ONTAP 所有。您不能将证书已过期的集群添加到Unified Manager中、如果证书已过期、则应在添加集群之前重新生成该集群。有关生成证书的信息、请参见知识库(KB)文章 https://["如何在System Manager用户界面中续订ONTAP 自签名证书"^]。



* Unified Manager 服务器上必须有足够的空间。如果数据库目录中已占用的空间超过 90% ，则系统将阻止您向服务器添加集群。


对于 MetroCluster 配置，必须同时添加本地和远程集群，并且必须正确配置这些集群。

.步骤
. 在左侧导航窗格中，单击 * 存储管理 * > * 集群设置 * 。
. 在 Cluster Setup 页面上，单击 * 添加 * 。
. 在添加集群对话框中，指定所需的值，例如集群的主机名或 IP 地址，用户名，密码和端口号。
+
您可以将集群管理 IP 地址从 IPv6 更改为 IPv4 或从 IPv4 更改为 IPv6 。下一个监控周期完成后，新 IP 地址将反映在集群网格和集群配置页面中。

. 单击 * 提交 * 。
. 在授权主机对话框中，单击 * 查看证书 * 以查看有关集群的证书信息。
. 单击 * 是 * 。
+
保存集群详细信息后、您可以看到用于集群相互TLS通信的证书。

+
如果未启用基于证书的身份验证、则Unified Manager仅在首次添加集群时才会检查证书。Unified Manager 不会检查对 ONTAP 的每次 API 调用的证书。



发现新集群的所有对象后， Unified Manager 将开始收集过去 15 天的历史性能数据。这些统计信息是使用数据连续性收集功能收集的。添加集群后，此功能会立即为您提供超过两周的集群性能信息。数据连续性收集周期完成后，系统会默认每五分钟收集一次实时集群性能数据。

[NOTE]
====
由于收集 15 天的性能数据需要占用大量 CPU 资源，因此建议您错开添加新集群的时间，以便不会在太多集群上同时运行数据连续性收集轮询。此外，如果您在数据连续性收集期间重新启动 Unified Manager ，则收集将暂停，并且性能图表中会显示缺少的时间范围。

====
[TIP]
====
如果您收到一条错误消息，指出无法添加集群，请检查两个系统上的时钟是否未同步，以及 Unified Manager HTTPS 证书的开始日期是否晚于集群上的日期。您必须确保时钟使用 NTP 或类似服务进行同步。

====
* 相关信息 *

link:../config/task_install_ca_signed_and_returned_https_certificate.html#example-certificate-chain["安装 CA 签名并返回的 HTTPS 证书"]
