---
permalink: install-linux/qsg-linux.html 
sidebar: sidebar 
keywords: quick start guide, QSG, Linux QSG, RHEL QSG, quick installation 
summary: 基于 Linux 平台的 Unified Manager 快速入门指南。 
---
= Linux 安装快速入门说明
:allow-uri-read: 




== 系统要求

* 操作系统：基于 x86_64 架构的 Red Hat Enterprise Linux 和 CentOS 7.x 和 8.x 版，使用操作系统安装程序的 * 软件选择 * 选项中的 " 带 GUI 的服务器 " 基础环境安装
* RAM ： 12 GB ， CPU ：总计 9572 MHz
* 可用磁盘空间： ` /opt/netapp/data` 目录中有 100 GB 磁盘空间，根分区中有 50 GB 磁盘空间。对于单独挂载的 ` /opt` 和 ` /var/log` 目录，请确保 ` /opt` 具有 15 GB ， ` /var/log` 具有 16 GB ， ` /tmp` 具有 10 GB 可用空间。


有关详细的系统要求以及在安全站点中安装产品的信息，请参见 link:../install-linux/concept_requirements_for_install_unified_manager.html["Unified Manager 的安装要求"] 和 link:http://mysupport.netapp.com/matrix["互操作性表"]。



== 安装 Active IQ Unified Manager



=== 下载安装程序：

. 下载 `ActiveIQUnifiedManager-<version>.zip` 安装包。
. 在下载安装文件的目录中，运行：
+
` # unzip ActiveIQUnifiedManager-<version>.zip`





=== 验证存储库配置

配置 Red Hat Enterprise Linux 或 CentOS 存储库的过程因站点而异。您可以使用安装包中包含的 `pre_install_check.sh` 脚本验证操作系统的配置。如果您的系统已连接到 Internet ，则会自动收到有关设置 Red Hat Enterprise Linux 或 CentOS 存储库的说明。

` # sudo ./pre_install_check.sh`



=== 安装 Unified Manager

Unified Manager 使用 `yum` 实用程序安装软件和任何相关软件。由于 Red Hat Enterprise Linux 或 CentOS 的映像各不相同，因此安装的软件包取决于映像中的软件。`yum` 实用程序可确定要安装的相关软件包。如果您需要有关相关软件包的详细信息，请参见 link:../install-linux/reference_red_hat_and_centos_software_and_installation_requirements.html["Linux 软件和安装要求"]。

要安装 Unified Manager ，请以 root 用户身份或使用 `sUdo` 从解压缩安装文件的目录运行以下命令：

` # yum install netapp-um<version>.x86_64.rpm`

或

` % sudo yum install netapp-um<version>.x86_64.rpm`

安装结束时，将显示连接到 Unified Manager Web UI 的信息。如果无法连接到 Web UI ，请参阅软件随附的 `reADME` 文件，了解有关端口 443 限制的详细信息。
