---
permalink: install-linux/reference_red_hat_software_and_installation_requirements.html 
sidebar: sidebar 
keywords: linux software, installation requirements, system, authorization,  requirements 
summary: 安装 Unified Manager 的 Linux 系统需要特定版本的操作系统和支持软件。 
---
= Linux 软件和安装要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
安装 Unified Manager 的 Linux 系统需要特定版本的操作系统和支持软件。



== 操作系统软件

Linux 系统必须安装以下版本的操作系统和支持软件：

* Red Hat Enterprise Linux 8.x和9.4版、基于x86_64架构。


有关受支持的Red Hat Enterprise Linux版本的最新完整列表、请参见互操作性表。

http://mysupport.netapp.com/matrix["mysupport.netapp.com/matrix"^]

此服务器应专用于运行 Unified Manager 。服务器上不应安装任何其他应用程序。由于公司法规的原因、您的Linux系统上可能安装了漏洞扫描程序(如Quulis)。您应在安装Unified Manager之前禁用漏洞扫描程序、以防止安装失败。


NOTE: 在内部(Unified Manager和漏洞扫描程序安装在同一个VM上)或外部扫描虚拟机(VM)时、漏洞扫描程序(如Qu固 件)可能会导致CPU使用率较高 (其中Unified Manager和漏洞扫描程序安装在两个不同的服务器上、漏洞扫描程序将扫描安装Unified Manager的VM)。此问题描述通常会导致VM无响应并影响Unified Manager服务。因此、NetApp建议在安装了Unified Manager的虚拟机中禁用漏洞扫描程序。如果无法禁用扫描程序、请在非工作时间扫描虚拟机、并在扫描完成后重新启动服务。



== 第三方软件

Unified Manager 部署在 WildFly Web 服务器上。WildFlY 26.1.3与Unified Manager捆绑在一起并进行了配置。

以下第三方软件包是必需的，但 Unified Manager 不提供这些软件包。这些软件包会在安装期间由 `yum` 安装程序自动安装，前提是您已按照以下各节所述配置存储库。

* MySQL Community Edition 8.0.37版(来自MySQL存储库)。
* OpenJDK 11.0.23版(来自Red Hat Extra Enterprise Linux Server存储库)
* Python 3.9.x (来自Red Hat Extra Enterprise Linux Server存储库)
* p7zip 16.02 或更高版本（从 Red Hat Extra Packages for Enterprise Linux 存储库）


[NOTE]
====
在升级任何第三方软件之前，您必须关闭正在运行的 Unified Manager 实例。第三方软件安装完成后，您可以重新启动 Unified Manager 。

====


== 用户授权要求

在 Linux 系统上安装 Unified Manager 可以由 root 用户执行，也可以由非 root 用户使用 `sudo` 命令执行。



== 安装要求

下面列出了在系统上安装Red Hat Enterprise Linux和关联存储库的最佳实践。以不同方式安装或配置的系统或在外部（在云中）部署的系统可能需要执行其他步骤，并且 Unified Manager 可能无法在此类部署中正常运行。

* 您必须根据Red Hat最佳实践安装Red Hat Enterprise Linux、并且应选择以下默认选项、这需要选择"`S带有GUI`的服务器"基础环境。
* 在Red Hat Enterprise Linux上安装Unified Manager时、系统必须能够访问相应的存储库、以便安装程序可以访问和安装所有必需的软件依赖项。
* 要使 `yum` 安装程序在 Red Hat Enterprise Linux 存储库中查找相关软件，您必须在 Red Hat Enterprise Linux 安装期间或之后使用有效的 Red Hat 订阅注册系统。
+
有关 Red Hat 订阅管理器的信息，请参见 Red Hat 文档。

* 要在系统上成功安装所需的第三方实用程序，您必须启用适用于 Enterprise Linux 的额外软件包（ EPEL ）存储库。
+
如果您的系统上未配置 EPEL 存储库，则必须手动下载并配置该存储库。

+
请参见 link:task_manually_configure_epel_repository.html["手动配置 EPEL 存储库"]。

* 如果未安装正确版本的 MySQL ，则必须启用 MySQL 存储库才能在系统上成功安装 MySQL 软件。
+
如果系统上未配置 MySQL 存储库，则必须手动下载并配置该存储库。

+
请参见 link:task_manually_configure_mysql_repository.html["手动配置 MySQL 存储库"]。



如果您的系统无法访问 Internet ，并且存储库未从已连接 Internet 的系统镜像到未连接的系统，则应按照安装说明确定系统的外部软件依赖关系。然后、您可以将所需软件下载到已连接Internet的系统、并将文件复制 `.rpm`到计划安装Unified Manager的系统。要下载项目和软件包、必须使用 `yum install`命令。您必须确保两个系统运行相同的操作系统版本、并且订阅许可证适用于相应的Red Hat Enterprise Linux。

[NOTE]
====
您不能从此处列出的存储库以外的存储库安装所需的第三方软件。从 Red Hat 存储库安装的软件专为 Red Hat Enterprise Linux 而设计，并且符合 Red Hat 最佳实践（目录布局，权限等）。来自其他位置的软件可能不遵循这些准则，这可能发生原因会导致 Unified Manager 安装失败，或者在未来升级时可能会出现发生原因问题。

====


== 端口 443 要求

Red Hat Enterprise Linux的通用映像可能会阻止对端口443的外部访问。由于存在此限制，您可能无法在安装 Unified Manager 后连接到管理员 Web UI 。运行以下命令允许通用Red Hat Enterprise Linux上的所有外部用户和应用程序访问端口443。

` # firewall-cmd -zone=public -add-port=443/tcp -perf持久 ； firewall-cmd -reload`

您必须在`S带有GUI`的服务器"基础环境中安装Red Hat Enterprise Linux。它提供了 Unified Manager 安装说明使用的命令。在其他基础环境中，可能需要安装其他命令来验证或完成安装。如果 `firewall-cmd`您的系统上不提供、则必须运行以下命令来安装它：

` # sudo yum install firewalld`

在运行命令之前，请联系您的 IT 部门，了解您的安全策略是否需要其他操作步骤。

[NOTE]
====
应在Red Hat系统上禁用THP (透明的大页面)。启用后，在某些情况下，如果某些进程占用过多内存并被终止，则可以关闭发生原因 Unified Manager 。

====