---
permalink: install-linux/task_upgrade_mysql_on_linux.html 
sidebar: sidebar 
keywords: upgrade, mysql, linux 
summary: 您可以在安装了 Unified Manager 的 Linux 服务器上升级到较新版本的 MySQL ，以获取安全漏洞修复。 
---
= 在 Linux 上升级 MySQL
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在安装了 Unified Manager 的 Linux 服务器上升级到较新版本的 MySQL ，以获取安全漏洞修复。如果系统上安装的 MySQL 版本早于 8.0.25 ，则 Unified Manager 9.10 升级过程会自动将 MySQL 升级到 8.0.25 。您不应将 MySQL 从早期版本独立升级到 8.0.25 。

* 您需要的内容 *

对于安装了 Unified Manager 的 Linux 系统，您必须具有 root 权限。

您只能将 MySQL 8.0.25 的基本版本升级到更高版本，以便进行次要更新。

.步骤
. 以 root 用户身份登录到 Unified Manager 主机。
. 在目标系统上下载最新的 MySQL Community Server ` .rpm` 软件包。
. 将捆绑包解压缩到目标系统上的目录。
. 在取消绑定后，您会在目录中获得多个 ` .rpm` 软件包，但 Unified Manager 仅需要以下 rpm 软件包：
+
** mysql-commune-client-8.0.25
** mysql-commune-libs-8.0.25
** mysql-commune-server-8.0.25
** mysql-commune-common-8.0.25
** mysql-commune-client-plugins-8.0.25 删除所有其他 ` .rpm` 软件包。但是，将所有软件包安装在 rpm 软件包中不会出现发生原因错误。


. 按所示顺序停止 Unified Manager 服务和关联的 MySQL 软件：
+
`systemctl stop ocieau`

+
`systemctl stop ocie`

+
`systemctl stop mysqld`

. 使用以下命令调用 MySQL 升级：
+
`yum install * 。 rpm`

+
*` .rpm` 是指下载较新版本 MySQL 的目录中的 ` .rpm` 软件包。

. 按所示顺序启动 Unified Manager ：
+
`systemctl start mysqld`

+
`systemctl start ocie`

+
`systemctl start ocieau`


