---
permalink: events/concept_guidelines_for_adding_alerts.html 
sidebar: sidebar 
keywords: guidelines, adding, alerts 
summary: 您可以根据资源添加警报，例如集群，节点，聚合或卷以及特定严重性类型的事件。作为最佳实践，您可以在添加任何关键对象所属的集群后为该对象添加警报。 
---
= 添加警报的准则
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以根据资源添加警报，例如集群，节点，聚合或卷以及特定严重性类型的事件。作为最佳实践，您可以在添加任何关键对象所属的集群后为该对象添加警报。

您可以使用以下准则和注意事项创建警报，以便有效地管理系统：

* 警报问题描述
+
您应为此警报提供一个问题描述，以帮助您有效地跟踪警报。

* Resources
+
您应确定哪些物理或逻辑资源需要警报。您可以根据需要包括和排除资源。例如，如果要通过配置警报来密切监控聚合，则必须从资源列表中选择所需的聚合。

+
如果选择资源类别，例如 * + User or Group Quotas之后，您将收到该类别中所有对象的警报。

+
[NOTE]
====
选择集群作为资源不会自动选择该集群中的存储对象。例如，如果为所有集群的所有严重事件创建警报，则只会收到集群严重事件的警报。您不会收到节点，聚合等上的严重事件警报。

====
* 事件严重性
+
您应确定指定严重性类型的事件（严重，错误，警告）是否应触发警报，如果是，则应触发哪种严重性类型。

* 选定事件
+
如果您根据生成的事件类型添加警报，则应确定哪些事件需要警报。

+
如果您选择事件严重性，但未选择任何单个事件（如果您将 " 选定事件 " 列留空），则会收到此类别中所有事件的警报。

* 操作
+
您必须提供接收通知的用户的用户名和电子邮件地址。您还可以将 SNMP 陷阱指定为通知模式。您可以将脚本与警报关联，以便在生成警报时执行这些脚本。

* 通知频率
+
您可以将警报配置为在指定时间内向收件人重复发送通知。您应确定警报的事件通知处于活动状态的时间。如果要在事件确认之前重复发送事件通知，则应确定重复发送通知的频率。

* 执行脚本
+
您可以将脚本与警报关联。生成警报时会执行脚本。


