---
permalink: events/reference_event_details_page.html 
sidebar: sidebar 
keywords: event, details, page 
summary: 在事件详细信息页面中，您可以查看选定事件的详细信息，例如事件严重性，影响级别，影响区域和事件源。此外，您还可以查看追加信息，了解可通过哪些修复方法来解析问题描述。 
---
= 事件详细信息页面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在事件详细信息页面中，您可以查看选定事件的详细信息，例如事件严重性，影响级别，影响区域和事件源。此外，您还可以查看追加信息，了解可通过哪些修复方法来解析问题描述。

* * 事件名称 *
+
事件的名称以及上次查看事件的时间。

+
对于非性能事件，当事件处于 " 新增 " 或 " 已确认 " 状态时，上次看到的信息未知，因此会隐藏。

* * 事件问题描述 *
+
事件的简短问题描述。

+
在某些情况下，事件问题描述会提供触发事件的原因。

* * 争用组件 *
+
对于动态性能事件，此部分显示的图标表示集群的逻辑组件和物理组件。如果某个组件处于争用状态，则其图标会圈出并以红色突出显示。

+
有关此处显示的组件的问题描述，请参见 _Cluster 组件及其可能发生争用的原因。



" 事件信息 " ， " 系统诊断 " 和 " 建议的操作 " 部分将在其他主题中进行介绍。



== 命令按钮

命令按钮可用于执行以下任务：

* * 注释图标 *
+
用于添加或更新有关事件的注释，并查看其他用户留下的所有注释。



* 操作菜单 *

* * 分配给我 *
+
将事件分配给您。

* * 分配给他人 *
+
打开分配所有者对话框，在此可以将事件分配或重新分配给其他用户。

+
将事件分配给用户时，系统会将用户的名称以及事件分配时间添加到选定事件的事件列表中。

+
您也可以通过将所有权字段留空来取消分配事件。

* * 确认 *
+
确认选定事件，以使您不再收到重复的警报通知。

+
确认事件后，您的用户名以及确认事件的时间将添加到选定事件的事件列表（确认者）中。确认事件后，您将负责管理该事件。

* * 标记为已解决 *
+
用于将事件状态更改为已解决。

+
解决某个事件时，系统会将您的用户名和事件解决时间添加到选定事件的事件列表（解决者）中。对事件采取更正操作后，必须将事件标记为已解决。

* * 添加警报 *
+
显示添加警报对话框，在此可以为选定事件添加警报。


