---
permalink: events/reference_storage_vm_events.html 
sidebar: sidebar 
keywords: storage, vm events, impact area, availability, configuration, performance, security 
summary: Storage VM 事件可为您提供有关 Storage VM （ SVM ）状态的信息，以便您可以监控潜在问题。事件按影响区域分组，并包括事件和陷阱名称，影响级别，源类型和严重性。 
---
= Storage VM 事件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage VM （ Storage Virtual Machine ，也称为 SVM ）事件可为您提供有关 Storage VM （ SVM ）状态的信息，以便您可以监控潜在问题。事件按影响区域分组，并包括事件和陷阱名称，影响级别，源类型和严重性。

星号（ * ）表示已转换为 Unified Manager 事件的 EMS 事件。



== 影响区域：可用性

|===
| 事件名称（陷阱名称） | 影响级别 | 源类型 | severity 


 a| 
SVM CIFS 服务已关闭（ ocumEvtVserverCifsServiceStatusDown ）
 a| 
意外事件
 a| 
SVM
 a| 
严重



 a| 
SVM CIFS 服务未配置（不适用）
 a| 
事件
 a| 
SVM
 a| 
信息



 a| 
尝试连接不存在的 CIFS 共享 * （ nbladeCifsNoPrivShare ）
 a| 
意外事件
 a| 
SVM
 a| 
严重



 a| 
CIFS NetBIOS 名称冲突 * （ nbladeCifsNbNameConflict ）
 a| 
风险
 a| 
SVM
 a| 
error



 a| 
CIFS 卷影复制操作失败 * （ cifsShadow CopyFailure ）
 a| 
风险
 a| 
SVM
 a| 
error



 a| 
多个 CIFS 连接 * （ nbladeCifsManyAus ）
 a| 
风险
 a| 
SVM
 a| 
error



 a| 
已超过最大 CIFS 连接数 * （ nbladeCifsMaxOpenSameFile ）
 a| 
风险
 a| 
SVM
 a| 
error



 a| 
已超过每个用户的 CIFS 连接数上限 * （ nbladeCifsMaxSessPerUsrConn ）
 a| 
风险
 a| 
SVM
 a| 
error



 a| 
SVM FC/FCoE 服务已关闭（ ocumEvtVserverFcServiceStatusDown ）
 a| 
意外事件
 a| 
SVM
 a| 
严重



 a| 
SVM iSCSI 服务已关闭（ ocumEvtVserverIscsiServiceStatusDown ）
 a| 
意外事件
 a| 
SVM
 a| 
严重



 a| 
SVM NFS 服务已关闭（ ocumEvtVserverNfsServiceStatusDown ）
 a| 
意外事件
 a| 
SVM
 a| 
严重



 a| 
SVM FC/FCoE 服务未配置（不适用）
 a| 
事件
 a| 
SVM
 a| 
信息



 a| 
未配置 SVM iSCSI 服务（不适用）
 a| 
事件
 a| 
SVM
 a| 
信息



 a| 
未配置 SVM NFS 服务（不适用）
 a| 
事件
 a| 
SVM
 a| 
信息



 a| 
SVM 已停止（ ocumEvtVserverDown ）
 a| 
风险
 a| 
SVM
 a| 
警告



 a| 
AV 服务器太忙，无法接受新的扫描请求 * （ nbladeVscanConnBackPressure）
 a| 
风险
 a| 
SVM
 a| 
error



 a| 
没有用于病毒扫描的 AV 服务器连接 * （ nbladeVscanNoScannerConn ）
 a| 
意外事件
 a| 
SVM
 a| 
严重



 a| 
未注册 AV 服务器 * （ nbladeVscanNoRegd扫描 程序）
 a| 
风险
 a| 
SVM
 a| 
error



 a| 
无响应 AV 服务器连接 * （ nbladeVscanConnInactive ）
 a| 
事件
 a| 
SVM
 a| 
信息



 a| 
未经授权的用户尝试访问 AV 服务器 * （ nbladeVscanBadUserPrivAccess ）
 a| 
风险
 a| 
SVM
 a| 
error



 a| 
AV 服务器发现病毒 * （ nbladeVscanVirusDetected-）
 a| 
风险
 a| 
SVM
 a| 
error

|===


== 影响区域：配置

|===
| 事件名称（陷阱名称） | 影响级别 | 源类型 | severity 


 a| 
已发现 SVM （不适用）
 a| 
事件
 a| 
SVM
 a| 
信息



 a| 
SVM 已删除（不适用）
 a| 
事件
 a| 
集群
 a| 
信息



 a| 
SVM 已重命名（不适用）
 a| 
事件
 a| 
SVM
 a| 
信息

|===


== 影响区域：性能

|===
| 事件名称（陷阱名称） | 影响级别 | 源类型 | severity 


 a| 
已违反 SVM IOPS 严重阈值（ ocumSvmIopsIncident ）
 a| 
意外事件
 a| 
SVM
 a| 
严重



 a| 
已违反 SVM IOPS 警告阈值（ ocumSvmIopsWarning ）
 a| 
风险
 a| 
SVM
 a| 
警告



 a| 
已违反 SVM MB/ 秒严重阈值（ ocumSvmMbpsIncident ）
 a| 
意外事件
 a| 
SVM
 a| 
严重



 a| 
已违反 SVM MB/ 秒警告阈值（ ocumSvmMbpsWarning ）
 a| 
风险
 a| 
SVM
 a| 
警告



 a| 
已违反 SVM 延迟严重阈值（ ocumSvmLatencyIncident ）
 a| 
意外事件
 a| 
SVM
 a| 
严重



 a| 
已违反 SVM 延迟警告阈值（ ocumSvmLatencyWarning ）
 a| 
风险
 a| 
SVM
 a| 
警告

|===


== 影响区域：安全性

|===
| 事件名称（陷阱名称） | 影响级别 | 源类型 | severity 


 a| 
已禁用审核日志（ ocumVserverAudit 日志已禁用）
 a| 
风险
 a| 
SVM
 a| 
警告



 a| 
已禁用登录横幅（ ocumVserverLoginBannerDisabled ）
 a| 
风险
 a| 
SVM
 a| 
警告



 a| 
SSH 正在使用不安全的密码（ ocumVserverSSHInsecure ）
 a| 
风险
 a| 
SVM
 a| 
警告



 a| 
已更改登录横幅（ ocumVserverLoginBannerChanged ）
 a| 
风险
 a| 
SVM
 a| 
警告



 a| 
已禁用 Storage VM 反勒索软件监控（已禁用反勒索软件服务）
 a| 
风险
 a| 
SVM
 a| 
警告



 a| 
已启用 Storage VM 反勒索软件监控（学习模式）（ antiRansomwareSvmStateDryrun ）
 a| 
事件
 a| 
SVM
 a| 
信息



 a| 
适用于反勒索软件监控的 Storage VM （学习模式）（ ocumEvtSvmArwCandidt ）
 a| 
事件
 a| 
SVM
 a| 
信息

|===