---
permalink: events/task_upload_new_active_iq_rules_file.html 
sidebar: sidebar 
keywords: upload, new, active iq AIQ rules, rules file, CA secure rules, config advisor rules 
summary: Unified Manager 会自动检查新的 Active IQ 规则文件，并在存在较新规则时下载新文件。但是，在无法访问外部网络的站点中，您需要手动上传规则文件。 
---
= 上传新的 Active IQ 规则文件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager会自动检查是否存在新的Active IQ 事件(规则)文件、如果存在较新的规则、则会下载新文件。但是，在无法访问外部网络的站点中，您需要手动上传规则文件。


NOTE: Active IQ 规则也称为Config Advisor (CA)安全规则。

如果在没有网络连接的站点中安装Unified Manager或将Unified Manager升级到特定版本、则捆绑的Active IQ 规则将自动可上传。但是、建议您大约每月从NetApp支持站点下载一次新的规则文件、以确保生成更新后的事件、并且存储系统仍能以最佳状态运行。

.开始之前
* 必须启用Active IQ 门户事件报告。默认情况下，此功能处于启用状态。有关信息，请参见 link:../config/concept_active_iq_platform_events.html["启用 Active IQ 门户事件"]。
* 您必须从 NetApp 支持站点下载规则文件。
+
规则文件位于： https://mysupport.netapp.com/api/content-service/staticcontents/content/public/tools/unifiedmanager/ca/secure_rules.zip[]



.步骤
. 在可访问网络的计算机上，导航到 NetApp 支持站点并下载当前规则 ` .zip` 文件。
+
捆绑的规则软件包包括规则存储库、数据源和NetApp知识库文章。

+

NOTE: 在Windows系统上、在没有网络连接的站点中、NetApp知识库文章默认不会与安装程序捆绑在一起。您可以从支持站点下载_secure rules.zip文件并将其上传、以查看所有规则的知识库文章。

. 将规则文件传输到可带入安全区域的某些介质，然后将其复制到安全区域的系统。
. 在左侧导航窗格中，单击 * 存储管理 * > * 事件设置 * 。
. 在 * 事件设置 * 页面中，单击 * 上传规则 * 按钮。
. 在 * 上传规则 * 对话框中，导航到您下载的规则 ` .zip` 文件并选择该文件，然后单击 * 上传 * 。
+
此过程可能需要几分钟时间。



规则文件将在 Unified Manager 服务器上解压缩。在受管集群在午夜后生成AutoSupport 文件后、Unified Manager将根据规则文件检查集群、并根据需要生成新的风险和意外事件。

有关详细信息、请参见此知识库(KB)文章： https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/Active_IQ_Unified_Manager/How_to_update_AIQCASecure_rules_manually_in_Active_IQ_Unified_Manager["如何在Active IQ Unified Manager 中手动更新AIQCASecure规则"]。
