---
permalink: data-protection/concept_types_of_snapmirror_protection.html 
sidebar: sidebar 
keywords: types, snapmirror, protection, consistency group, snapmirror business continuity, smbc, sm-bc 
summary: 根据数据存储拓扑的部署情况，您可以使用 Unified Manager 配置多种类型的 SnapMirror 保护关系。所有形式的 SnapMirror 保护均可提供故障转移灾难恢复保护，但在性能，版本灵活性和多个备份副本保护方面提供不同的功能。 
---
= SnapMirror 保护的类型
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
根据数据存储拓扑的部署情况，您可以使用 Unified Manager 配置多种类型的 SnapMirror 保护关系。所有形式的 SnapMirror 保护均可提供故障转移灾难恢复保护，但在性能，版本灵活性和多个备份副本保护方面提供不同的功能。



== 传统 SnapMirror 异步保护关系

传统的 SnapMirror 异步保护可在源卷和目标卷之间提供块复制镜像保护。

在传统 SnapMirror 关系中，镜像操作的执行速度比在其他 SnapMirror 关系中更快，因为镜像操作基于块复制。但是，传统的 SnapMirror 保护要求目标卷与源卷在同一主要版本（例如 8.x 到 8.x 或 9.x 到 9.x ）中运行的 ONTAP 软件版本相同或更高的次要版本。不支持从 9.1 源复制到 9.0 目标，因为该目标运行的是早期的主要版本。



== 采用版本灵活复制的 SnapMirror 异步保护

采用版本灵活复制的 SnapMirror 异步保护可在源卷和目标卷之间提供逻辑复制镜像保护，即使这些卷运行的是不同版本的 ONTAP 8.3 或更高版本软件（例如 8.3 至 8.3.1 ， 8.3 至 9.1 或 9.2.2 至 9.2 ）也是如此。

在使用版本灵活复制的 SnapMirror 关系中，镜像操作的执行速度不如在传统 SnapMirror 关系中那样快。

由于执行速度较慢，具有版本灵活的复制保护的 SnapMirror 不适合在以下任一情况下实施：

* 源对象包含 1000 多万个要保护的文件。
* 受保护数据的恢复点目标为两小时或更短。（也就是说，目标位置必须始终包含可恢复的镜像数据，这些数据不超过源位置的数据两小时。）


在列出的任一情况下，都需要更快地执行基于块复制的默认 SnapMirror 保护。



== SnapMirror 异步保护，具有版本灵活的复制和备份选项

SnapMirror 异步保护具有版本灵活的复制和备份选项，可在源卷和目标卷之间提供镜像保护，并可在目标上存储镜像数据的多个副本。

存储管理员可以指定从源到目标镜像哪些 Snapshot 副本，还可以指定这些副本在目标上保留多长时间，即使这些副本在源上被删除也是如此。

在使用版本灵活的复制和备份选项的 SnapMirror 关系中，镜像操作的执行速度不如在传统 SnapMirror 关系中那样快。



== SnapMirror 统一复制（镜像和存储）

SnapMirror 统一复制允许您在同一目标卷上配置灾难恢复和归档。与 SnapMirror 一样，统一数据保护会在您首次调用时执行基线传输。默认统一数据保护策略 `MirrorAndVault` 下的基线传输会为源卷创建 Snapshot 副本，然后将该副本及其引用的数据块传输到目标卷。与 SnapVault 一样，统一数据保护不会在基线中包含较早的 Snapshot 副本。



== 采用严格同步的 SnapMirror 同步保护

采用 " `s` " 同步的 SnapMirror 同步保护可确保主卷和二级卷始终是彼此的真实副本。如果在尝试向二级卷写入数据时复制失败，则指向主卷的客户端 I/O 将中断。



== 采用常规同步的 SnapMirror 同步保护

采用 " `re同步` " 的 SnapMirror 同步保护不要求主卷和二级卷始终是彼此的真实副本，从而确保主卷的可用性。如果在尝试向二级卷写入数据时发生复制失败，则主卷和二级卷将不再同步，客户端 I/O 将继续向主卷写入。

[NOTE]
====
从 " 运行状况：所有卷 " 视图或 " 卷 / 运行状况 " 详细信息页面监控同步保护关系时， " 还原 " 按钮和 " 关系 " 操作按钮不可用。

====


== SnapMirror 同步业务连续性

ONTAP 9.8 及更高版本提供了 SnapMirror 业务连续性（ SM-BC ）功能，您可以使用它来保护具有 LUN 的应用程序，使应用程序能够透明地进行故障转移，从而确保在发生灾难时的业务连续性。

您可以通过 Unified Manager 发现和监控集群和 Storage Virtual Machine 上可用的一致性组（ CG ）的同步 SnapMirror 关系。AFF 集群或全 SAN 阵列（ ASA ）集群支持 SM-BC ，其中主集群和二级集群可以是 AFF 或 ASA 。SM-BC 使用 iSCSI 或 FCP LUN 保护应用程序。

查看受 SM-BC 关系保护的卷和 LUN 时，您可以获得保护关系，卷清单中的一致性组，一致性组关系的保护拓扑，一致性组关系的历史数据以及长达一年的一致性组关系的历史数据。您也可以下载此报告。此外，您还可以查看一致性组关系的摘要，搜索一致性组关系的支持以及获取有关受一致性组保护的卷的信息。

在关系页面上，您还可以对受一致性组保护的源和目标存储对象及其关系进行排序，筛选和扩展保护。

要了解有关 SnapMirror 同步业务连续性的更多信息，请参见 link:https://docs.netapp.com/us-en/ontap/smbc/index.html["适用于 SM-BC 的 ONTAP 9 文档"]。
