---
permalink: data-protection/reference_create_storage_virtual_machine_associations_wizard.html 
sidebar: sidebar 
keywords: create, storage, virtual machine, peers, wizard 
summary: 通过创建 Storage Virtual Machine 对等方向导，您可以对源和目标 Storage VM 建立对等关系，以便在 SnapMirror 和 SnapVault 保护关系中使用。 
---
= 创建 Storage Virtual Machine 对等方向导
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过创建 Storage Virtual Machine 对等方向导，您可以对源和目标 Storage VM 建立对等关系，以便在 SnapMirror 和 SnapVault 保护关系中使用。



== 选择源

通过 " 选择源 " 面板，您可以选择 Storage VM 对等方中的源 Storage VM 或主 Storage VM 。

* * 任意 *
+
用于在任何 Storage VM 源与一个或多个目标或二级 Storage VM 之间创建对等关系。这意味着，当前需要保护的所有现有 Storage VM 以及未来创建的任何 Storage VM 都会与指定的目标 Storage VM 建立对等关系。例如，您可能希望将来自不同位置的多个不同源的应用程序备份到一个位置的一个或多个目标 Storage VM 。

* * 单个 *
+
用于将特定源 Storage VM 与一个或多个目标 Storage VM 建立对等关系。例如，如果要为数据必须彼此分离的多个客户端提供存储服务，请选择此选项将特定 Storage VM 源与仅分配给该客户端的特定 Storage VM 目标关联起来。

* * 无（外部） *
+
用于在源 Storage VM 和目标 Storage VM 的外部灵活卷之间创建关联。

+
** Storage Virtual Machine
+
列出可用源 Storage VM 的名称

** 集群
+
列出每个 Storage VM 所在的集群



* * 允许此类关系 *
+
用于选择关联的关系类型：

+
** SnapMirror
+
指定 SnapMirror 关系作为对等类型。选择此选项可将数据从选定源复制到选定目标。

** SnapVault
+
指定 SnapVault 关系作为对等类型。选择此选项可将选定主位置备份到选定二级位置。







== 选择保护目标

通过创建 Storage Virtual Machine 对等方向导的选择保护目标面板，您可以选择复制或复制数据的位置。每个集群只能在一个目标 Storage VM 上创建对等关系。



== 命令按钮

命令按钮可用于执行以下任务：

* * 下一步 *
+
进入向导中的下一页。

* * 返回 *
+
返回到向导中的上一页。

* * 完成 *
+
应用所做的选择并创建关联。

* * 取消 *
+
丢弃所做的选择并关闭创建 Storage Virtual Machine 对等方向导。


