---
permalink: data-protection/task_create_snapmirror_relationship_from_health_volumes.html 
sidebar: sidebar 
keywords: create, snapmirror, protection, relationship, health, volumes view 
summary: 使用运行状况：所有卷视图，您可以通过在同一个 Storage VM 上选择多个卷来一次创建多个 SnapMirror 保护关系。 
---
= 从运行状况：所有卷视图创建 SnapMirror 保护关系
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用运行状况：所有卷视图，您可以通过在同一个 Storage VM 上选择多个卷来一次创建多个 SnapMirror 保护关系。

* 您需要的内容 *

* 您必须具有应用程序管理员或存储管理员角色。
* 您必须已设置 Workflow Automation 。


在以下情况下，不会显示 * 保护 * 菜单：

* 如果 RBAC 设置不允许执行此操作：例如，您只有操作员权限
* 当卷 ID 未知时：例如，当您具有集群间关系且尚未发现目标集群时


.步骤
. 在 * 运行状况：所有卷 * 视图中，选择要保护的卷。
+
或者，要在同一 SVM 上创建多个保护关系，请在运行状况：所有卷视图中选择一个或多个卷，然后单击工具栏上的 * 保护 * > * SnapMirror * 。

+
此时将显示配置保护对话框。

. 单击 * SnapMirror * 可查看 * SnapMirror * 选项卡并配置目标信息。
. 根据需要单击 * 高级 * 设置空间保证，然后单击 * 应用 * 。
. 完成 * 目标信息 * 区域和 * SnapMirror * 选项卡中的 * 关系设置 * 区域。
. 单击 * 应用 * 。
+
此时将返回到运行状况：所有卷视图。

. 单击 * 运行状况：所有卷视图 * 顶部的保护配置作业链接。
+
如果仅创建一个保护关系，则会显示作业详细信息页面；但是，如果要创建多个保护关系，则会显示与保护操作关联的所有作业的列表。

. 执行以下操作之一：
+
** 如果只有一个作业，请单击 * 刷新 * 以更新与保护配置作业关联的任务列表和任务详细信息，并确定作业完成的时间。
** 如果您有多个作业：
+
... 单击作业列表中的作业。
... 单击 * 刷新 * 可更新与保护配置作业关联的任务列表和任务详细信息，并确定作业完成的时间。
... 使用 * 返回 * 按钮返回到筛选列表并查看其他作业。






根据您在配置期间指定的目标 SVM 或在 " 高级 " 设置中启用的选项，生成的 SnapMirror 关系可能是以下几种可能的变体之一：

* 如果您指定的目标 SVM 在与源卷相同或更新版本的 ONTAP 下运行，则默认结果为基于块复制的 SnapMirror 关系。
* 如果您指定的目标 SVM 在与源卷版本相同或更新的 ONTAP 下运行，但您在 " 高级 " 设置中启用了版本灵活复制，则会生成具有版本灵活复制功能的 SnapMirror 关系。
* 如果您指定的目标 SVM 在低于源卷的 ONTAP 早期版本下运行，并且早期版本支持版本灵活复制，则会自动生成具有版本灵活复制功能的 SnapMirror 关系。

