---
permalink: data-protection/task_create_storage_virtual_machine_svm_associations.html 
sidebar: sidebar 
keywords: create, storage, vm, peers 
summary: 通过创建 Storage Virtual Machine 对等方向导，合作伙伴保护应用程序可以将源 Storage VM 与目标 Storage VM 相关联，以便用于 SnapMirror 和 SnapVault 关系。在初始配置目标卷时，合作伙伴应用程序会使用这些关联来确定要选择的资源。 
---
= 创建 Storage VM 对等方
:icons: font
:imagesdir: ../media/


[role="lead"]
通过创建 Storage Virtual Machine 对等方向导，合作伙伴保护应用程序可以将源 Storage VM 与目标 Storage VM 相关联，以便用于 SnapMirror 和 SnapVault 关系。在初始配置目标卷时，合作伙伴应用程序会使用这些关联来确定要选择的资源。

* 您需要的内容 *

* 要关联的 Storage VM 必须已存在。
* 您必须具有应用程序管理员或存储管理员角色。


对于任何源 Storage VM 和关系类型，您只能在每个目标集群上选择一个目标 Storage VM 。

使用 delete 和 create 函数更改关联仅会影响未来的配置操作。它不会移动现有目标卷。

.步骤
. 在左侧导航窗格中，单击 * 保护 * > * Storage VM 对等方 * 。
. 在 * SVM 对等方 * 页面中，单击 * 创建 * 。
+
此时将启动创建 Storage Virtual Machine 对等方向导。

. 选择以下源之一：
+
** * 任意 *
+
如果要在任何主 Storage VM 源与一个或多个目标 Storage VM 之间创建关联，请选择此选项。这意味着，当前需要保护的所有现有 Storage VM 以及未来创建的任何 Storage VM 都会与指定的目标 Storage VM 相关联。例如，您可能希望将来自不同位置的多个不同源的应用程序备份到一个位置的一个或多个目标 Storage VM 。

** * 单个 *
+
如果要选择与一个或多个目标 Storage VM 关联的特定源 Storage VM ，请选择此选项。例如，如果要为数据必须彼此分离的多个客户端提供存储服务，请选择此选项将特定 Storage VM 源与仅分配给该客户端的特定 Storage VM 目标关联起来。

** * 无（外部） *
+
如果要在源 Storage VM 与目标 Storage VM 的外部灵活卷之间创建关联，请选择此选项。



. 选择要创建的一种或两种保护关系类型：
+
** * SnapMirror *
** * SnapVault *


. 单击 * 下一步 * 。
. 选择一个或多个 Storage VM 保护目标。
. 单击 * 完成 * 。

