---
permalink: data-protection/view-protection-status.html 
sidebar: sidebar 
keywords: view, volume, protection status, dashboard protection card, protection panel, protection widget 
summary: '" 数据保护 " 页面提供了数据中心中所有受保护卷的数据保护详细信息的整体视图。' 
---
= 查看卷保护状态
:icons: font
:imagesdir: ../media/


[role="lead"]
" 数据保护 " 页面提供了单个集群中所有受保护卷或数据中心中所有集群的数据保护详细信息的整体视图。

单击信息板上 " 数据保护 " 面板顶部的右箭头即可查看这些详细信息。此屏幕包含两个部分。在信息板上选择所有集群时， * 所有集群 * 部分将显示受 SnapMirror 关系和 Snapshot 副本保护的数据中心级别的所有集群的保护状态。您可以在 * 单个集群 * 部分中选择一个特定集群，以查看该集群中受保护卷的状态。

如果您在信息板上选择了一个集群，则此页面将显示该集群上受保护卷的详细信息。

您可以将鼠标悬停在每个条形图上以查看相应的计数。单击条形图可转到卷屏幕，其中包含选定的相应卷。单击每个事件中的链接将转到 " 事件 " 详细信息页面。您可以单击 * 查看全部 * 链接以查看事件管理清单页面中的所有活动保护事件。

.步骤
. 在左侧导航窗格中，单击 * 信息板 * 。
. 根据您要查看所有受监控集群或单个集群的数据保护状态，选择 * 所有集群 * 或从下拉菜单中选择一个集群。
. 单击数据保护面板中的右箭头。




== 数据保护页面

" 数据保护 " 页面显示了所有集群中受保护卷的以下面板。


NOTE: 对于 Snapshot 副本的卷计数，源卷和目标卷均会考虑在内。对于 SnapMirror 关系，将计算已启用读取和写入的源卷。不考虑目标卷和根卷。SnapMirror 计数包括源和目标位于相同或不同集群上的卷数。

* * Snapshot 概述 * ： Snapshot 副本保护的卷概述，例如：
+
** 受 Snapshot 副本保护和不受 Snapshot 副本保护的卷总数。
+

NOTE: 要将某个卷视为受保护卷，应启用该卷的 Snapshot 副本计划。

** 正在使用或超过 Snapshot 副本预留空间的卷总数。此值对于查看已用磁盘空间量或计算删除一个或多个 Snapshot 副本后可回收的空间非常重要。


* * SnapMirror 概述 * ： SnapMirror 策略保护的卷概述，例如：
+
** 受相应 SnapMirror 策略保护的卷数，例如卷 SnapMirror 关系， Storage VM 灾难恢复（ SVM-DR ）及其组合。
** SnapMirror 关系中出现滞后的卷总数。如果卷具有多个 SnapMirror 关系，则会选择最差的滞后。




单个集群列表显示特定集群的 SnapMirror 关系和 Snapshot 保护的状态。

* * Snapshot 副本分析 * 详细介绍了以下信息：
+
** Snapshot 副本的各个事件，包括过去 24 小时内引发的事件。
** 受 Snapshot 副本保护和不受 Snapshot 副本保护的卷的详细图表。
** 卷使用，未使用和违反预留的 Snapshot 副本容量。您可以使用此信息计算删除一个或多个 Snapshot 副本后已利用或可回收的空间。
** 卷的细分按其 Snapshot 副本的数量计算。返回的 Snapshot 副本数量仅适用于联机且可用的卷。


* * SnapMirror 分析 * 详细介绍了以下信息：
+
** 为 SnapMirror 关系引发的各个事件，包括过去 24 小时内引发的事件
** 由每个 SnapMirror 策略（例如卷 SnapMirror 关系， Storage VM 灾难恢复（ SVM-DR ）及其组合）保护的卷数。
** 受 SnapMirror 关系类型（例如异步镜像，异步存储，异步镜像存储， StrictSync ， SnapMirror 业务连续性（ SMBC ）一致性组和 Sync ）保护的卷数。
** 关系状态为 " 运行状况良好 " 或 " 运行状况不正常 " 的卷数。只有当卷的所有 SnapMirror 关系运行状况良好时，才会将此卷视为运行状况良好。
** 按恢复点目标（ RPO ）滞后持续时间的速率对卷计数进行细分。



